### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [AAndyProgram/SCrawler#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by AAndyProgram** [comment]
I don't know how to do this and how it works

**Comment by TechnologyClassroom** [comment]
1. In GitHub, start at the [repository page](https://github.com/AAndyProgram/SCrawler/).
2. Click on the `Add file` button and select `Create new file` or click [here](https://github.com/AAndyProgram/SCrawler/new/master).
3. In the `Name of your file...` text box, type in `LICENSE.md` and a new button will appear.
4. Click on the `Choose a license template` button.
5. Click on the license that you would like to use.  I would recommend `GNU General Public License v3.0` or `GNU Affero General Public License v3.0`.  A brief description of what the license does will show on the screen.
6. Click on the `Review and Submit` button.
7. Beneath `Commit new file` enter a commit description.  I like to use the precise SPDX identifier for the commit such as `AGPL-3.0-or-later.
8. Click on the `Commit directly to the x branch.` radio button.
9. Click on the `Commit new file` button.

**Comment by AAndyProgram** [comment]
Okay. Thank you. I have googled some information about licenses and I need time to study it. I don't quite understand if there are any restrictions impose on me, and if I understood correctly, I have to do something with code... Sorry, I am still don't understand this.

**Comment by TechnologyClassroom** [comment]
The owner of the copyright is not restricted with the license.

With GPL licenses there are additionally standard license headers that can go in applicable files, but not everyone uses them.  `REUSE` is a tool that can automatically apply them after some configuration.  Instructions about standard license headers are in the last section of the GPL.

**Comment by AAndyProgram** [comment]
I created a license right now. If I understand correctly, I should insert the text below at the top of each code file, am I right?

```
<one line to give the program's name and a brief idea of what it does.>
Copyright (C) <year>  <name of author>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by TechnologyClassroom** [comment]
@AAndyProgram That's right.

Just change the first line to something like:

`Copyright (C) 2021 Andy Thompson`

**Comment by AAndyProgram** [comment]
Done. Thank you for your help.
