### ISSUE TITLE
Not downloading all user (Reddit) submitted post

### ISSUE THREAD

**Issue by tayser1** [AAndyProgram/SCrawler#10]
Expected result:
Download all images and videos of user

Issue:
Grabs only 24 files 

Tested on this user link:
https://www.reddit.com/user/Fantastic-Skill5156

**Comment by AAndyProgram** [comment]
> Issue: Grabs only 24 files

1. I don't know why you only got 24 files. I got 44 photo and 6 videos.
2. Posts not created by the user (crossposts) are always skipped by the program.


**I have reviewed this profile and confirmed that the profile download is incomplete (even 44 photo and 6 videos).** The program only grabs 77 posts for reasons I don't understand. I need time to check the code and the Reddit API (maybe something has changed).

**Comment by AAndyProgram** [comment]
[Fixed](https://github.com/AAndyProgram/SCrawler/releases/latest)
