### ISSUE TITLE
[BUG] Cannot download Gfycat video

### ISSUE THREAD

**Issue by twosushi** [AAndyProgram/SCrawler#101]
Cannot download Gfycat video

**To Reproduce**
1.  
<details>
  <summary>NSFW USER URL</summary>

https://www.reddit.com/user/calicoo/submitted/
</details>

2. Add link, Download data 
3. Video(s) do not download specifically the 2 newest submissions.

<details>
  <summary>NSFW Links</summary>

I have the cutest pussy and I love to drip for you [vid]
https://gfycat.com/AgreeableLazyImago
On Chrome this redirects to https://www.redgifs.com/watch/agreeablelazyimago
On Firefox this redirects to https://v3.redgifs.com/watch/agreeablelazyimago

Want to see me edge until I'm dripping? [vid]
https://gfycat.com/ImpureCluelessAmericanratsnake
On Chrome this redirects to https://www.redgifs.com/watch/impurecluelessamericanratsnake
On Firefox this redirects to https://v3.redgifs.com/watch/impurecluelessamericanratsnake
</details>

Not sure if its because the user who posted these on Gfycat account deleted their account there, you can only see it on the Chrome redirect, says "user deleted".
Not sure why the two browsers show different pages.

Hopefully you can reproduce the bug.
Thanks!

**Comment by AAndyProgram** [comment]
Got it. I think I can fix it.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

*Sorry for taking so long.*

**Comment by twosushi** [comment]
> _Sorry for taking so long._

It's all good. :smile:
Thanks for the update.
