### ISSUE TITLE
[BUG] TikTok not downloading

### ISSUE THREAD

**Issue by OMGerEDU** [AAndyProgram/SCrawler#102]
**Profile URL**: https://www.tiktok.com/@developertowelie

**Log data**
```
2023-01-29 05:29:36: Message: The operation has timed out
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Tools.Web.Clients.Base.ResponserErrorProcessor.ProcessException(Exception ex, ErrorsDescriber e, String URL, Object NullArg, String Caller)
	   at PersonalUtilities.Tools.Web.Clients.Responser.Internal_GetResponse(Object URL, String PayLoad, ErrorsDescriber e)
	   at SCrawler.API.TikTok.UserData.DownloadDataF(CancellationToken Token)
```

Scraping TikTok channel,
I tried both Reddit and Tiktok, Reddit seems to work,
I tried also on VMware to check if my PC was the problem, but I guess I am just missing something

**Release information (please complete the following information):**
Windows 10
64Bit
4.8.1 Net framework (wasn't sure what V I had, then updated to last, both version done the same)

Would be glad to receive some help, probably just a rookie mistake but I hope someone will help me solve it :\

**Comment by AAndyProgram** [comment]
TikTok is currently not downloading.
https://github.com/AAndyProgram/SCrawler/issues/84

**Comment by OMGerEDU** [comment]
Big oof, your software seems great, and I did managed to use Twitter, Reddit and IG but Tiktok was what I looked for originally,
Any ETA if that should be fixed?

**Comment by AAndyProgram** [comment]
>Any ETA if that should be fixed?

No. Currently I have no plans to fix TikTok. TikTok doesn't have proper API documentation.

**Comment by Aston77** [comment]
Is the main problem currently the scrolling issue you mentioned earlier in the year #75 ?

**Comment by AAndyProgram** [comment]
Not only. There is another problem with connection to the site. I'm waiting for (and if) yt-dlp fix their tik-tok parser and I'll update mine.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
