### ISSUE TITLE
[BUG] Video downloader doesnt workig for xh, ph, xv

### ISSUE THREAD

**Issue by blackgur** [AAndyProgram/SCrawler#106]
Downloading videos for ph, xh, xv does not work.
The program caches the video, but the end result is that the final video files are not there. 
Instead, all videos go into "missing posts".
https://i.imgur.com/bn0MCTi.png

Downloading for reddit and twitter works fine.

I'm using scrawler 2023.2.5.0 x64
Windows 11 x64

**Comment by blackgur** [comment]
I solved the problem.
The problem was the Cyrillic alphabet in the path.

**Comment by AAndyProgram** [comment]
I think it's a duplicate of #99, but I didn't get feedback with the problem URL so I can't fix it.
If you want, you can post a link to the problematic video here or text me on Discord (AndyProgram#3804) and I'll try to fix it.

**Comment by blackgur** [comment]
I don't think it's the same thing.
I had a problem that windows explorer had a path with Russian letters to scrawler.exe

So absolutely any profiles from ph, xh, xv would not load but only cached.

**Comment by AAndyProgram** [comment]
Okay. Like I said "if you want". I think there is a problem with some characters, but until I get an example, I can't fix it. In your case I need the path you used in your language. I'm sure I can create the same path to identify the error. But if you don't want to, then fine.

**Comment by blackgur** [comment]
Try creating a folder named "папка_тест", put a clean build of scrawler there, and try downloading something from ph, xv, or xh

**Comment by AAndyProgram** [comment]
Okay

**Comment by AAndyProgram** [comment]
Confirmed. I would appreciate a link to a video named in your language to fix the problem with these characters.

**Comment by blackgur** [comment]
I tried to download the profile https://rt.pornhub.com/model/dominatrixannette
But there is no video with Cyrillic in the title. So I think it's because of the Cyrillic in the name of the folder where the scrawler is

**Comment by AAndyProgram** [comment]
Unfortunately no. SCrawler has successfully downloaded parts of the video. There's a problem when he tried to combine them. I think the folder name is enough to fix this, but to be sure, it's better to have a link to a video containing these characters.

Okay, I'll try to fix it for the next release. But if you see a video with these characters, please send me a link.

**Comment by AAndyProgram** [comment]
And thank you for providing the folder name. Finally I can identify the error.

**Comment by username112299** [comment]
у меня такая же проблема. я писал тебе на редите несколько месяцев назад а ты не ответил.

**Comment by username112299** [comment]
и еще поменяй иконку программы на что нибудь более подходящее для таких программ. и убери из инфо проги инфу что ты пидрила, это никому не интересно.

**Comment by blackgur** [comment]
Also, there are difficulties with videos with emoji in the title.
Sample: https://www.pornhub.com/view_video.php?viewkey=ph61f92c8fb188b

**Comment by AAndyProgram** [comment]
>у меня такая же проблема. я писал тебе на редите несколько месяцев назад а ты не ответил.

@username112299, thanks for your report too. If I understand you correctly, I don't remember you texting me on Reddit. If so, sorry if I didn't answer. You can always send me a message on Discord (AndyProgram#3804).

>и еще поменяй иконку программы на что нибудь более подходящее для таких программ.

I set the rainbow icon just for fun. SCrawler stands out from the crowd. Personally, I like this icon. But if you suggest another icon, I'll think about.

**And please, write in English if you can.**

**Comment by AAndyProgram** [comment]
> Also, there are difficulties with videos with emoji in the title. Sample: https://www.pornhub.com/view_video.php?viewkey=ph61f92c8fb188b

Got it. Thank you.

**Comment by username112299** [comment]
да ты правильно понял. ладно прощаю но в следующий раз отвечай когда тебе пишут, понял?
хорошо хоть тут быстро отвечаешь
на счет иконки, он слишком выделяется. у таких программ обычно значок в виде стрелки загрузки, а не какой то пидорский. если я скину тебе значок ты сменишь эту пидорскую иконку? и хватит пропагандировать что ты пидрила вонючий, все уже поняли что ты пидорасина, гандон тупой, бесите уже
я не хочу писать на английском, используй гугл переводчик. ты же прочел мои сообщения значит умеешь пользоваться, вот и пользуйся.
и вообще добавь Русский язык в программу. что тут сложного? так сложно русифицировать меню? я тебе уже писал чтоб ты добавил Русский язык

**Comment by AAndyProgram** [comment]
>да ты правильно понял. ладно прощаю но в следующий раз отвечай когда тебе пишут, понял?

I'm sorry, but I'm not sure I completely understand you. Who are "they" who write to me?

>хорошо хоть тут быстро отвечаешь

I usually reply very quickly (within a few hours)

>на счет иконки, он слишком выделяется. у таких программ обычно значок в виде стрелки загрузки. если я скину тебе значок ты сменишь эту иконку?

I'll think about.

>я не хочу писать на английском, используй гугл переводчик. ты же прочел мои сообщения значит умеешь пользоваться, вот и пользуйся.

Okay. 😊 

>и вообще добавь Русский язык в программу. что тут сложного? так сложно русифицировать меню? я тебе уже писал чтоб ты добавил Русский язык

Someone already asked me about this. Translation of the program to other languages concerns not only the menu. These are messages, forms' elements, notifications, log messages, etc. I don't have the time or desire to waste time on this. SCrawler is not even translated into my native language. On the other hand, English is an international, well-known language. I remember only one request to translate. I guess all other people are satisfied with this.

----

**Please, don't post all your questions in this thread. This thread is about character bugs. If you want to ask something, you should create a new issue.**

**Comment by username112299** [comment]
какие они? я говорю если тебе пишут люди отвечай сразу, понял?
ну и что что инглиш международный, не все его знают и не все его обязаны знать. просто добавь Русский язык. уже не один запрос а два получается. @blackgur тоже Русский, он наверняка за то чтобы добавить Русский язык. @blackgur ты же за то чтобы этот 3,14дор добавил Русский язык в программу? поддержи меня брат
и вообще отвечай нам на Русском, это же не сложно. сам же пишешь что на другом языке разговариваешь, значит на английский переводишь. вот и отвечай на Русском. мне не удобно твои сообщения переводить с английского
а что касается этой темы то не только с Русскими символами проблема. проблема бывает и с другими символами которые не английские

**Comment by AAndyProgram** [comment]
>какие они? я говорю если тебе пишут люди отвечай сразу, понял?

Excuse me, I already said that I usually reply very quickly (within a few hours)

>ну и что что инглиш международный, не все его знают и не все его обязаны знать. просто добавь Русский язык. уже не один запрос а два получается. @blackgur тоже Русский, он наверняка за то чтобы добавить Русский язык. @blackgur ты же за то чтобы этот 3,14дор добавил Русский язык в программу? поддержи меня брат

I don't understand at all. If you are talking about adding the Russian language to SCrawler, I guess I've already answered clearly enough.

>и вообще отвечай нам на Русском, это же не сложно. сам же пишешь что на другом языке разговариваешь, значит на английский переводишь. вот и отвечай на Русском. мне не удобно твои сообщения переводить с английского

What?!

>а что касается этой темы то не только с Русскими символами проблема. проблема бывает и с другими символами которые не английские

First time I hear about. I need an example.

**Comment by username112299** [comment]
слушай ты членососина давай отвечай быстрее. я почти час ждал пока ты ответишь тупая пидорская скотина
отвечай мне на Русском а не на английском, что не понятного, или ты не только пидор сраный но еще и тупой? и почему с вами пидрилами всегда так сложно
примеры потом скину

**Comment by AAndyProgram** [comment]
>отвечай быстрее. я почти час ждал пока ты ответишь

I'm sorry, but I answer as soon as possible. Forgive me for the delay, but I also have a life. If you want to chat faster, try contacting me on Discord.

>отвечай мне на Русском а не на английском, что не понятного

It's very difficult.

**Comment by username112299** [comment]
ничего сложного, отвечай на Русском как я требую

**Comment by AAndyProgram** [comment]
As you demand? Who are you to demand anything? I don't fully understand what you were talking about, I don't think Google is translating your messages correctly, but I don't like your tone. I am perfectly polite in dialogue, but it seemed to me that you were ordering me. About the language, I already answered: this will not happen. About the "demand": if you don't like SCrawler, you can always find another program. The program is free. I am develop SCrawler for myself and publish on GitHub because people found my program useful. If someone can't use it or doesn't like it, I'm fine.

**Comment by blackgur** [comment]
Clean it up and lock conversation until it is resolved by you. Thank you.

**Comment by AAndyProgram** [comment]
> Also, there are difficulties with videos with emoji in the title. Sample: https://www.pornhub.com/view_video.php?viewkey=ph61f92c8fb188b

Found a bug.
Will be fixed in the next version.

>Try creating a folder named "папка_тест", put a clean build of scrawler there, and try downloading something from ph, xv, or xh

Found a bug.
Actually, this is not my bug. This is an ffmpeg bug. Encoding transition or something.
1. I updated ffmpeg to the latest version.
2. Before executing I added the `chcp 1251` command to change the CMD code page.

Now everything is all right. A few days for testing.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Comment by AAndyProgram** [comment]
I've added cmd encoding setting. The default is 65001 (Unicode). In your case, you need to set this value to 1251. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
