### ISSUE TITLE
[REQUEST] xhamster: add the ability to download channels and creators 

### ISSUE THREAD

**Issue by ChrisTheDBA** [AAndyProgram/SCrawler#107]
**Is your feature request related to a problem? Please describe.**
The crawler only downloads from users in the format of https://xhamster.com/users/XXXXX and not other URLS.

**Describe the solution you'd like**
It would nice to be able get content from additional URL types like -
https://xhamster.com/channel/XXXXXX and https://xhamster.com/creators/XXXXXX

**Describe alternatives you've considered**
I have repeatedly tried downloading from these types of URLS. the program immediately returns with no content downloaded.

**Comment by AAndyProgram** [comment]
Replace "XXXXXX" with real links.

**Comment by ChrisTheDBA** [comment]
https://xhamster.com/creators/mirari or https://xhamster.com/channels/big-bad-divas

**Comment by AAndyProgram** [comment]
Okay, I'll think about the channels.

In the "creators" section, there is a link which directs you to the user's profile (https://xhamster.com/users/mirari_fap).

![image](https://user-images.githubusercontent.com/88590076/219990873-561d0aa7-6628-44f9-a3d4-c5557cdcb989.png)

**Comment by AAndyProgram** [comment]
The channels will be added to the next version. Is everything okay with the 'creators'?

**Comment by ChrisTheDBA** [comment]
Yes, the link to get to the user works. Thanks for the enhancement.

**Comment by AAndyProgram** [comment]
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
