### ISSUE TITLE
[REQUEST] Auto-scale images for download feed

### ISSUE THREAD

**Issue by blackgur** [AAndyProgram/SCrawler#108]
Add to the download feed an automatic resizing function to fit the screen size.
Sometimes the images are too big.
![image](https://user-images.githubusercontent.com/6291267/220105414-35388708-f657-4b6c-be13-4966ac6757ab.png)

**Comment by AAndyProgram** [comment]
I don't understand. The image (even in the picture you post) is already auto-scaled (widthwise) to fit the form. If you want to fit the image in height, you can just resize the form.

**Comment by blackgur** [comment]
You have autoscale only in width. I need both width and height.


>If you want to fit the image in height, you can just resize the form.
An example?

**Comment by AAndyProgram** [comment]
>You have autoscale only in width. I need both width and height.

How do you propose to do this? If I scale the image in width and heigh, most of the images will be smaller in width and there will be a lot of empty space in the window. It's not beautiful. Do you know the fact that in the [settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#feed) you can configure the display of more than one image in a row?

>An example?

Example? Resize the feed window and you'll see.

**Comment by blackgur** [comment]
> Do you know the fact that in the [settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#feed) you can configure the display of more than one image in a row?

My mistake. Increased the number of columns is more convenient!
Thanks for the answers.

**Comment by AAndyProgram** [comment]
You are welcome 😊 

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by AAndyProgram** [comment]
>I need both width and height.

Will be added in the next version.

**Comment by AAndyProgram** [comment]
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
