### ISSUE TITLE
getting "Twitter has invalid credentials" any ideas? have token and auth,..  need put in cookie ? thx

### ISSUE THREAD

**Issue by kocoman1** [AAndyProgram/SCrawler#11]
getting "Twitter has invalid credentials" any ideas? have token and auth,..  need put in cookie ? thx

**Comment by AAndyProgram** [comment]
Yes, you are right. Twitter requires two tokens and cookies.

**Comment by kocoman1** [comment]
I can't copy the cookie import from google chrome keeps saying its invalid

**Comment by kocoman1** [comment]
What cookie value from twitter do i copy?

**Comment by AAndyProgram** [comment]
>I can't copy the cookie import from google chrome keeps saying its invalid

Who says it?
