### ISSUE TITLE
Измени значок программы

### ISSUE THREAD

**Issue by username112299** [AAndyProgram/SCrawler#111]
Вот новый значок, поменяй на него или сделай хотя бы отдельный релиз с ним и без надписи о том что ты гомосексуалист. Никому не интересно что ты глиномес. Зачем ты всем сообщаешь что ты гомосек?
![загрузка](https://user-images.githubusercontent.com/103402042/222575502-7b190b7e-dfb1-47b2-bbf9-f565a1a8fcee.png)

**Comment by AAndyProgram** [comment]
1. Write in English.
2. What's wrong with the current program icon?
3. What do you mean by "clay maker"? I don't understand. I don't work with clay.
4. Does the fact that I'm gay bother you in any way?
5. Separate release? What for?

I don't like the icon you posted.

**Comment by username112299** [comment]
1. Нет. Используй гугл переводчик
2. Это значок для гомосеков, а я не гомосексуалист
3. Забей
4. Другие программисты просто выкладывают программы и не пишут что они гомосеки
5. Для меня. Сделай отдельный релиз для меня.

Значков могу накидать много

**Comment by AAndyProgram** [comment]
2. Congratulations
3. Okay
4. So what?
5. Really?!

**Comment by username112299** [comment]
4. Сделай значок без гомосятины
5. Да, сделай для меня отдельный релиз.

Напиши свой дискорд я пришлю тебе значки и все остальное что любят гомосеки

**Comment by AAndyProgram** [comment]
Dude, what badges are you talking about? My discord: AndyProgram#3804

**Comment by username112299** [comment]
Можно я тебе в дискорд пришлю значки для программы?

**Comment by AAndyProgram** [comment]
Yes

**Comment by username112299** [comment]
А ты правда гомосек?

**Comment by AAndyProgram** [comment]
Yes, I am.
