### ISSUE TITLE
Not downloading attachements on LPSG

### ISSUE THREAD

**Issue by jrd5656** [AAndyProgram/SCrawler#114]
Is there a way to get this program to also download images in attachments from posts? It skips all of those on LPSG but its fine with normal images.

**Comment by AAndyProgram** [comment]
Post url with attachment

**Comment by AAndyProgram** [comment]
Thank you for providing the link. I'll check, but not now. Now I'm very busy. LPSG is not an important site for me and has no meaning. So I'll check when I have time. Sorry.

----

*Actually I wrote a parser to download a single thread with 100+ pages. I currently don't have any profiles of this site in SCrawler. Some time ago I even considered removing it from SCrawler, but decided to keep it while it works. If someday this parser breaks, I won't fix it.*

**Comment by AAndyProgram** [comment]
Will be fixed in the next version (couple of weeks)

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
