### ISSUE TITLE
PornHub. Error in the log with no Gif in the profile

### ISSUE THREAD

**Issue by blackgur** [AAndyProgram/SCrawler#116]
**Describe the bug**
I'm not sure if it's a bug or if it should be.
Error in the log with no Gif in the profile

**To Reproduce**
1. **Profile URL**:  https://www.pornhub.com/model/hubofcandy/
2. Try to download profile
3. See error in log

**Log data**
```
2023-03-22 03:55:29: [Hubofcandy] - [PornHub] - model_hubofcandy: gifs downloading error [https://www.pornhub.com/model/hubofcandy/gifs]
	Text became null when parsing with PrePatterns(0)
	parameter name: Text
2023-03-22 03:55:29: Message: Text became null when parsing with PrePatterns(0)
	parameter name: Text
	HelpLink:
	StackTrace:    в PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	в PersonalUtilities.Functions.RegularExpressions.RegexFunctions.RegexFields[T](String Text, IEnumerable`1 PrePatterns, IEnumerable`1 Fields, Object[] Arguments)
	в SCrawler.API.PornHub.UserData.DownloadUserGifs(CancellationToken Token)
``` 

**Expected behavior**
Just no error in the log. Since I know that there is no gif in the profile. (But they'll show up someday.)

**Release information (please complete the following information):**

- Win11
- x64
- 2023.3.5.0

**Comment by AAndyProgram** [comment]
Okay, obviously I missed something while debugging. I'll find this exception and hide it.

**Comment by AAndyProgram** [comment]
Will be fixed in the next version.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
