### ISSUE TITLE
Instagram post

### ISSUE THREAD

**Issue by 89z** [AAndyProgram/SCrawler#12]
Is it possible to download just one post?

https://www.instagram.com/p/CZVEugIPkVn/

**Comment by AAndyProgram** [comment]
Yes, it is. Just click the "Download video (F2)" button in the main window and add the post URL. It also downloads photos from Instagram. Don't forget your Instagram [settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-settings).

**Comment by 89z** [comment]
Thank you!
