### ISSUE TITLE
[REQUEST] Add site piggiesgetfed.com

### ISSUE THREAD

**Issue by NikitaForsov** [AAndyProgram/SCrawler#122]
Please, add site https://piggiesgetfed.com/
This site only has videos of fagots eating shit. You should like it.
https://piggiesgetfed.com/hot-young-pig-savors-and-swallows-his-mates-shit/
https://piggiesgetfed.com/asian-toilet-boy/
https://piggiesgetfed.com/push-a-turd-into-his-waiting-mouth/

**Comment by AAndyProgram** [comment]
1. NO!
2. Crazy?
3. Call me a "fagot" one more time and you'll be banned!
4. This site is disgusting!

**Comment by NikitaForsov** [comment]
I'm sorry, I meant on this site fags like you eat shit. Don't be shy, all fags do it. I like to see it.

**Comment by NikitaForsov** [comment]
I like your application
