### ISSUE TITLE
Instagram original quality

### ISSUE THREAD

**Issue by 89z** [AAndyProgram/SCrawler#13]
If I use Scrawler with this page:

https://www.instagram.com/p/CZVEugIPkVn/

I get 1080 x 1080 image. If I use a request like this:

~~~
GET /p/CZVEugIPkVn/?__a=1 HTTP/1.1
Host: www.instagram.com
User-Agent: Instagram 220.0.0.16.115 Android (99/9; density; 9999x9999; brand; model; device; platform
Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZXNzaW9ua...
~~~

I can get original quality, 1241 x 1241. Is it possible for Scrawler to get the better quality?

**Comment by AAndyProgram** [comment]
Yes, it should download exactly 1241. Checked right now and got a photo from your URL in 1241x1241.
![image](https://user-images.githubusercontent.com/88590076/152625909-3bda75e6-c125-4015-a0b7-1a5ae89ed747.png)

**Comment by 89z** [comment]
Do I have to log in? when I tried it, I just did anonymous

**Comment by AAndyProgram** [comment]
Yes. 
[Instagram settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-settings)

**Comment by 89z** [comment]
I see you had the same problem as me. It seems you get a different response depending on if youre logged in or not:

https://github.com/AAndyProgram/SCrawler/blob/5d5ce29f3696d9d17a545ab7524a57b81fc5f12f/SCrawler/API/Instagram/UserData.vb#L248-L260

**Comment by AAndyProgram** [comment]
So, is everything all right there? Did you download the full size?

**Comment by 89z** [comment]
I am going to work on another solution, but this was helpful. I was getting frustrated because Instagram has severe rate limiting, like one request per hour or something. Then I find out that they serve completely different JSON depending on if user is logged in or not. Originally I was thinking its a temporary issue, because I had noticed similar differences depending on which country you requested from. However seeing how you made that change like two weeks ago, it might be this way for a while. I think its dumb to serve totally different JSON like that, but I guess I have to deal with it.

**Comment by AAndyProgram** [comment]
The first algo allows you to get only the top profile photos. Not all photos! To get more, you must enter your credentials! Instagram is a closed network and these two unauthorized API functions were left by mistake, I guess!

**Comment by 89z** [comment]
what is  bypass 496?

**Comment by AAndyProgram** [comment]
> what is bypass 496?

Sorry, this is a typo. I mean 429 (too many requests)

**Comment by 89z** [comment]
I dont really get that problem myself. If I make too many anonymous requests, then I just get a redirect to login. Then after that I will login using `/api/v1/accounts/login/` and requests work again after that. When I was originally working on my login code, I did have some trouble with rate limiting, as when I was testing, I was making a bunch of login requests. However now that I finished the login code, I dont that problem. However in general I dont make a lot of request, but I do want the option for anonymous requests in my code.

**Comment by AAndyProgram** [comment]
I don't use OAuth

**Comment by 89z** [comment]
You should do it, its really easy:

~~~
POST /api/v1/accounts/login/ HTTP/1.1
Host: i.instagram.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Instagram 220.0.0.16.115 Android (99/9; density; 9999x9999; brand; model; device; platform

signed_body=SIGNATURE.{"device_id":"device_id",
"enc_password":"#PWD_INSTAGRAM:0:0:YourPassword","username":"YourUsername"}
~~~

**Comment by AAndyProgram** [comment]
For any authorization, the program must be registered through a dying network - facebook. I don't want to register there.

**Comment by 89z** [comment]
You dont have to register. Just make a request like above, then response will be like this:

~~~
HTTP/2.0 200 OK
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Alt-Svc: h3=":443"; ma=3600,h3-29=":443"; ma=3600
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Language: en
Content-Type: application/json; charset=utf-8
Cross-Origin-Embedder-Policy-Report-Only: require-corp;report-to="coep"
Cross-Origin-Opener-Policy: same-origin-allow-popups;report-to="coop"
Date: Sat, 05 Feb 2022 03:42:24 GMT
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Ig-Set-Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZX...
~~~

Then use `Ig-Set-Authorization` in future requests.

**Comment by AAndyProgram** [comment]
Okay. Where did you get the ```Bearer``` token?

**Comment by 89z** [comment]
1. make request to `/api/v1/accounts/login/` as shown above
2. in response will be `Ig-Set-Authorization` header
3. make further requests using `Authorization` header with value from step 2

**Comment by AAndyProgram** [comment]
Hm... Thank you. I'll check it out later!

**Comment by AAndyProgram** [comment]
> You should do it, its really easy:
> 
> ```
> POST /api/v1/accounts/login/ HTTP/1.1
> Host: i.instagram.com
> Content-Type: application/x-www-form-urlencoded
> User-Agent: Instagram 220.0.0.16.115 Android (99/9; density; 9999x9999; brand; model; device; platform
> 
> signed_body=SIGNATURE.{"device_id":"device_id",
> "enc_password":"#PWD_INSTAGRAM:0:0:YourPassword","username":"YourUsername"}
> ```

Where did you find that? URL?

> signed_body=SIGNATURE.{"device_id":"device_id",
> "enc_password":"#PWD_INSTAGRAM:0:0:YourPassword","username":"YourUsername"}

Is it a payload or that?
>enc_password

What does "enc" mean? Encoded password? So what's the encoding?

>"#PWD_INSTAGRAM:0:0:YourPassword"

This is completely incomprehensible! Should I replace all this text with the password or just the text "YourPassword"?
Anyway, I have a 409 error.

Can you make an example with login = 1234 and password = 5678

**Comment by 89z** [comment]
Sorry I dont think these questions are on topic. I was trying to be helpful, but now youre asking too many questions. If I am to proceed, it would need to be as part of a contract. Good luck.

**Comment by AAndyProgram** [comment]
>it would need to be as part of a contract

WHAT? The program is free and you want to get money from me! What contract?! You posted a non-working query and when I asked a simple "how-to" thing, you want money from me! GOOD BUY!
In this case, never contact me for help again and don't open new issues! Next time I will be deaf and blind to your questions and your issue will be removed and ignored.
