### ISSUE TITLE
All of my profiles turned red and I can't download anything from twitter.

### ISSUE THREAD

**Issue by Jasper42** [AAndyProgram/SCrawler#134]
I don't think I did anything, everything was working fine until yesterday. There's nothing in the Logs.
![image](https://github.com/AAndyProgram/SCrawler/assets/42576945/372a3fd9-407c-403a-9833-6db07e813ff5)
![image](https://github.com/AAndyProgram/SCrawler/assets/42576945/a35cd73b-73b3-417c-bd55-47234e241650)

**Comment by blackgur** [comment]
I observe the same thing. Updating the authorization and token did not bring results

**Comment by AAndyProgram** [comment]
Twitter has completely moved to the new API. You can track this issue [here](https://github.com/AAndyProgram/SCrawler/discussions/104#discussioncomment-6078804).

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
