### ISSUE TITLE
Twitter DL stopped working

### ISSUE THREAD

**Issue by happygolucky919** [AAndyProgram/SCrawler#135]
Twitter credentials were inputted, and I was adding users and downloading media for dozens of users without a hitch. Then I added a dozen users and decided to DL them all at once in a queue by highlighting all 12 and hitting download. I immediately get “All data downloaded” and all 12 users name turn red. Nothing was downloaded and the red name implies the profiles were deleted, but the Twitter accounts still exist?

Now **ALL** the users on my twitter list won't download anything new either. I get an immediate “All data downloaded” and their names individually turn red. Nothing has changed, but my twitter section seems to be bugged after I tried to download a dozen at once. I don't know if it was something else or a coincidence with another issue.

Re-entering credentials doesn't fix it. Logs are empty, they show nothing wrong.

**Comment by AAndyProgram** [comment]
Twitter has completely moved to the new API. You can track this issue [here](https://github.com/AAndyProgram/SCrawler/discussions/104#discussioncomment-6078804).

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
