### ISSUE TITLE
Instagram configuration not showing everything

### ISSUE THREAD

**Issue by m0rpheux** [AAndyProgram/SCrawler#136]
i've redownloaded latest scrawler and it still shows the instagram authorization like in the picture attached so i cannot see the boxes for x-ig-app-id, ix-ig-www-claim, etc 
![screenshot 180](https://github.com/AAndyProgram/SCrawler/assets/4407448/f68b8138-da84-4c97-a22c-4d5c980beced)

**Comment by AAndyProgram** [comment]
Your monitor resolution is less than the height of the form. I'll try to fix it in the next release.
