### ISSUE TITLE
[BUG] Error when specifying network paths 

### ISSUE THREAD

**Issue by LigerXT5** [AAndyProgram/SCrawler#14]
"Not accurate" is a loose term that comes to mind. Let me elaborate.

Before I updated just now, the Settings and Saved! folders were pointing to a folder on my network. Not over a network drive, and for reasons will not use a network drive.
(Typed file names are examples, not actual, refer to screenshot.)

Network listing would be \\Truenas\sharename\downloads\RedditStuff\SCrawler

Saving a navigated to spot, and reopening Settings or similar: C:\file\path\to\Scrawler\Truenas\sharename\downloads\RedditStuff\SCrawler
Both the Settings and Reddit.

The only reason I split the two, I have SCrawler saved in my dropbox location, while where it saves content to is a network drive. 
Moving SCrawler to my network share, and running it from, results in basically same file pathing. \\Truenas\sharename\downloads\RedditStuff\SCrawler\Truenas\sharename\downloads\RedditStuff\SCrawler\.

As far as I can, without actually testing it, SCrawler must run and save on the local machine. If I had to guess, the main harddrive at worst?

This is after copying SCrawler to the same network share as the saves. Then changing settings to point to the new location, closing, then opening settings. Restarting SCrawler does not resolve it (Closing by the icon by the clock).

![Capture](https://user-images.githubusercontent.com/771392/152651015-039c8312-9658-46f1-ae8c-6ee95bd8bfa8.JPG)

Before copying to network drive, running on second local harddrive.
![Capture](https://user-images.githubusercontent.com/771392/152651284-281328a4-fd7d-4fee-b3c5-e55d70776568.JPG)

Back on 2.0.1:
![Capture](https://user-images.githubusercontent.com/771392/152651722-f6818276-04b9-49bf-847c-4ed91d34922e.JPG)

**Comment by AAndyProgram** [comment]
Hello.
Thank you for your report. Yes, I checked right now and confirm that the bug exists. I don't know what's going on (because I don't remember any changes to those modules), but you're right, it's a bug. I'll try to fix it ASAP. Until then, I advise you to use 2.0.0.1 version if it works for you.

To be sure. Does 2.0.0.1 work well with network drives?

**Comment by LigerXT5** [comment]
Correct, 2.0.0.1. On launch, it states I'm on 2.0.0.1, and there's a new update.

**Comment by AAndyProgram** [comment]
I found an error. That was my fault. Last time I updated my SFile structure with some unix formats and this algo was incorrect and broke network paths. I very rarely use network paths and missed this error. So tomorrow I'll post a new release.
Thanks again for reporting the bug.

**Comment by AAndyProgram** [comment]
Fixed! Please download version [2.0.0.4](https://github.com/AAndyProgram/SCrawler/releases/latest)

If I understand correctly, you save your saved posts to DropBox. Now, if you wish, you can specify a special path for saved posts (Settings-Settings-Reddit/Instagram-Saved posts path). Leave it blank to use the default path.

Have a nice day :-)
