### ISSUE TITLE
Gif Downloaded From Reddit Are Static

### ISSUE THREAD

**Issue by aminiqmal39** [AAndyProgram/SCrawler#141]
A lot of gif i have download from reddit are static, not playing at all. I do check the gif on reddit and the one downloaded with same media id. gif at reddit work just fine. There are some gif that are playing but most of the gif are not playing at all.

Also, the file size of the gif are too small for a gif, i guess, it have to do with the quality of the downloader or extractor.

**Comment by AAndyProgram** [comment]
Please post the profile URL you're trying to download.

**Comment by aminiqmal39** [comment]
Here the profile url 
https://www.reddit.com/r/gifMemes/

**Comment by AAndyProgram** [comment]
Confirmed.

**Comment by AAndyProgram** [comment]
Will be fixed in next version

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

----

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
