### ISSUE TITLE
Downloading Reddit Saved posts

### ISSUE THREAD

**Issue by AlexTu2** [AAndyProgram/SCrawler#143]
My goal is to archive my reddit's saved posts.

I mainly want the media content with subreddit information, poster name

I've tried using the documentation but I'm still having difficulties. 
The saved post button shows "host unavailable" for all hosts.
![image](https://github.com/AAndyProgram/SCrawler/assets/6798052/59be4851-48ee-486a-8f5f-72b9cad6a655)

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/wiki/Settings#reddit

**Comment by AlexTu2** [comment]
> https://github.com/AAndyProgram/SCrawler/wiki/Settings#reddit

@AAndyProgram 

I have the cookies, header, imgur client id all set, imported cookies via google chrome 

How can I make sure I've configured everything correctly? as it's not working

**Comment by AAndyProgram** [comment]
Did you set `Saved posts user name`?

>I have the cookies, header

What header?

**Comment by AAndyProgram** [comment]
> User agent header

I forgot about it :-)

Did you set `Saved posts user name`?

**Comment by AlexTu2** [comment]
> 

Nope, I have that set as well

**Comment by AAndyProgram** [comment]
Yes, you have to

**Comment by AlexTu2** [comment]
> Yes, you have to

I mean, I already have it set

**Comment by AAndyProgram** [comment]
And still nothing?

**Comment by AlexTu2** [comment]
> And still nothing?

Yeah, I've tried reopening the application

**Comment by AAndyProgram** [comment]
Excuse me, but how many cookies are displayed in the settings (number)?

**Comment by AlexTu2** [comment]
> Excuse me, but how many cookies are displayed in the settings (number)?

36

**Comment by AAndyProgram** [comment]
I can't test it right now but I'll check it tomorrow. As far as I can see, your settings are correct. I downloaded my saved posts yesterday and everything was fine. If it really doesn't downloaded, then Reddit has started rolling out a new API. If so, I can't help you. I think Reddit is RIP forever (at least for apps).

**Comment by AAndyProgram** [comment]
**Can't confirm**. I added a few saved posts and downloaded them all. Just to be clear: in the `https://reddit.com/user/UserName1` the username is `UserName1`

**Comment by AlexTu2** [comment]
> **Can't confirm**. I added a few saved posts and downloaded them all. Just to be clear: in the `https://reddit.com/user/UserName1` the 'Saved posts user name' is `UserName1`

I restarted my computer and it worked, I most likely didn't fully close the application after filling in the information. Thanks for your help!
