### ISSUE TITLE
Downloaded videos from xHamster are corrupted

### ISSUE THREAD

**Issue by pingzoo** [AAndyProgram/SCrawler#144]
Hey,

1st of all: Thank you for this tool.

I am making the first attempts with the scrawler and can't solve the following problem.

The videos from xHamster users are found and the download also starts, but the video files are only 150-250 kb in size.
There is no error message and no entry in the error log.

The download of picture albums is error-free.

The video download at ThisVid works fine as well.

Unfortunately I can't tell if I'm making a mistake in using it, or maybe it's a bug in the scrawler or a new "wall" in xHamster?

It happens on all URL. But here is an example:
https://www.xhamster.com/user/jens15

I use Windows 11, the directory where the program is started is: C:\SCrawler\.

I would be glad if you could check this.

Greetings
Felix

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

----

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
