### ISSUE TITLE
Instagram not downloading.

### ISSUE THREAD

**Issue by jeri2150** [AAndyProgram/SCrawler#148]
**Describe the bug**

**To Reproduce**
1. **Profile URL**: 
2. **Post URL**: 
3. Do something

<details>
<summary>Log data</summary>
<pre>
If the program log contains any data, replace this line with the log data. If the program log does not contain any data, write here about.
</pre>
</details>

**Expected behavior**

**Screenshots**

**Release information (please complete the following information):**
 - OS: [e.g. Windows 10, Windows 11]
 - Architecture: [e.g. x86, x64]
 - Version: [e.g. 2023.3.5.0]
 - NET.Framework version: 
 - ffmpeg version (command `ffmpeg -version`):
 - yt-dlp version (command `yt-dlp --version`):
 - gallery-dl version (command `gallery-dl --version`):

**Additional context**
Tired a few times to download the posts and they said download was complete, but does not download, I cliked on the add and the user profile was there and added, then when i hit download it said all data was complete, any help on what im doing wrong would be great.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram

**Comment by iampunisher2000** [comment]
I am having a similar issue where initially the app downloaded some profiles without any issues. But later on when I add any new profile it wont download and even the old profiles which downloaded successfully have this error in the log:
[STORIES] DOWNLOADING IS DISABLED UNTIL YOU UPDATE YOUR CREDENTIALS
What I have noticed is that the x-csrftoken value that I set manually following your instructions changes to something else after pressing download.

**Comment by AAndyProgram** [comment]
> [STORIES] DOWNLOADING IS DISABLED UNTIL YOU UPDATE YOUR CREDENTIALS

The log tells you what you need to do: update your credentials.

> What I have noticed is that the x-csrftoken value that I set manually following your instructions changes to something else after pressing download.

When downloading, SCrawler looks for a new token in the response headers. If it is found, SCrawler updates it. However, sometimes Instagram can log you out and you'll need to update your credentials.

**Comment by iampunisher2000** [comment]
Got it. Did all the steps again including deleting the cookies and adding them again and its running fine now. Thanks.

**Comment by jeri2150** [comment]
Hi I’m still having troubles not sure how to find the harsh I looked on network but don’t know what I’m looking for since I never used that menu before

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AAndyProgram** [comment]
I'm sorry. The settings guide is clear enough. Most people can configure it with no problem. If you can't configure it, you should find another (more easy) program. Have a nice day.

**Comment by iampunisher2000** [comment]
Under the network option you have to click the search (magnifying glass) -> a new panel will appear -> Put in "query_hash=" in the search bar of that -> You will get multiple places where that text is present, but usually the last place is where the correct hash is present, (atleast that was what it was in my case) Refresh the instagram page if the value isnt appearing. The hash value you are looking for is after the = sign and before the &variables part. Between those is the hash value. 
You will also find the other 
[x-csrftoken]
[x-ig-app-id]
[ix-ig-www-claim]
there at the bottom as well which you have to copy and paste.
Hope this helps.

**Comment by buzyinsta** [comment]
First I wanted to say thanks for this tool, it will help me in many repetitive tasks I have to do for my business. You rock!
Nevertheless, I'm running into issues.
I followed your instructions about the Instagram authorization settings (x-csrftoken , x-ig-app-id, ix-ig-www-claim, sec-ch-ua, sec-ch-ua-full-version-list, sec-ch-ua-platform-version, UserAgent). I managed to have it working once for an account but then it stopped working.
It's either looping at the stage "Instagram downloading 1/1 profiles' data" or goes directly to "Instagram all data completed". 
I'd be very grateful if someone could help me?

**Comment by AAndyProgram** [comment]
> First I wanted to say thank you for this tool, you rock!

Thank you! I'm glad you like it and it's a pleasure to read such kind words. 😊 

> I managed to have it working once for an account but then it stopped working.

Is there any data in the LOG? Instagram has very good error handling, so if your credentials have expired or you did have some other issue, you will see an error in the log. 👀 

If you've already seen the error and updated your credentials, don't forget to turn the download (`Download timeline` and `Download stories`) checkboxes back. ❗ 

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/c3bfd01b-5443-4706-9ce3-fa7d3a0642f6)

> It's either looping at the stage "Instagram downloading 1/1 profiles' data"

It's not "looping at the stage". SCrawler takes time to collect data. Remember that some profiles are huge. 😏 

> or goes directly to "Instagram all data completed".

If you see "Instagram all data completed" right after start, most likely that your credentials are missing or some download functions are disabled (I mean the checkboxes I described earlier). Also don't forget that Instagram requires cookies.

----

Btw, join my Discord server: https://discord.gg/uFNUXvFFmg

**And if you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by buzyinsta** [comment]
> It's not "looping at the stage". SCrawler takes time to collect data. Remember that some profiles are huge. 😏
Oh, that fixed everything. Indeed, the profiles I was trying to download had 3000+ posts. 
Thanks a lot

**Comment by akafanfan** [comment]
don't forget to turn the download (Download timeline and Download stories) checkboxes back. ❗ 
is very improtant
