### ISSUE TITLE
[REQUEST] It'd be nice if removing a username from the crawler wouldn't deleted the folder from /data/

### ISSUE THREAD

**Issue by SrGrafoasspee** [AAndyProgram/SCrawler#15]
Removing the user name/account from the crawler deletes the folder with all the pics and videos

It'd be better if the folder remains in the SCrawler_2.0.0.4_x64\Data\ subfolder

**Comment by AAndyProgram** [comment]
It's already there. When you delete a user, in the MessageBox click "Delete user only". The user will be removed from SCrawler, but the user data will remain.
