### ISSUE TITLE
Instagram: We suspect automated behavior on your account

### ISSUE THREAD

**Issue by AdyTZa619** [AAndyProgram/SCrawler#150]
Any problem if recive this message ? 
![image](https://github.com/AAndyProgram/SCrawler/assets/137645268/a247bb65-6df0-4964-ba8c-9422b3560718)

**Comment by AAndyProgram** [comment]
This is not a bug. Instagram can log you out. SCrawler has account protection. If you have entered incorrect credentials or are still trying to download something even when the log tells you that you must update your credentials, your account can be banned. **Read the [guide](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram) carefully.**
