### ISSUE TITLE
[REQUEST] Is possible to add https://www.eporner.com ?

### ISSUE THREAD

**Issue by lollos73** [AAndyProgram/SCrawler#152]
as a title is possible to add this site or tell me how add on program?
ty vm

**Comment by AAndyProgram** [comment]
No, sorry. I'm currently not accepting requests for new sites. If you know C# or VB.NET, you can create a plugin for SCrawler (read [here](https://github.com/AAndyProgram/SCrawler/wiki/Plugins) how to make a plugin).
