### ISSUE TITLE
Download Twitter Media by Hashtags/Username Mentions

### ISSUE THREAD

**Issue by jr8273** [AAndyProgram/SCrawler#153]
### Discussed in https://github.com/AAndyProgram/SCrawler/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **trumbladome** September  5, 2022</sup>

I have got the profile tool downloading but what i what like to do is download Videos (could include pictures) of media that has a specific hashtag or username mentioned this could be defined to a last 24 hours/48 hours/week/month etc

For example Avril Lavigne videos that mentions her twitter account
https://twitter.com/search?q=%40avrillavigne&src=typed_query&f=video
</div>

**Comment by AAndyProgram** [comment]
This will not be implemented, sorry.
