### ISSUE TITLE
Importing user list doesn't grab all users.

### ISSUE THREAD

**Issue by happygolucky919** [AAndyProgram/SCrawler#154]
I like to download user data onto my SSD C: drive. After I've accrued gig's of data I'll cut/paste Scrawler/Data to my archive HDD D: drive. That makes me lose my user list. So I'll import the data folder from my D: drive to grab all the users I've collected and restart the program, but it seems to randomly grab some users and not others, leading to an incomplete list. Attempting to import a single user says they're already on the list, but they clearly aren't.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/wiki#move-the-scrawler-data-to-a-new-location

**Comment by happygolucky919** [comment]
Thanks a bunch, AAndy!

**Comment by AAndyProgram** [comment]
You're welcome 😊
