### ISSUE TITLE
More verbose logging?

### ISSUE THREAD

**Issue by ekvq** [AAndyProgram/SCrawler#156]
Hi there!

I'm troubleshooting an issue with a profile from PornHub. I think that I've configured everything correctly, but all I get when downloading the profile is an "All data downloaded" notification but no actual content was scraped. Wondering if there's a setting somewhere that would show me more in the logs to see where it's failing.

Thanks!

**Comment by AAndyProgram** [comment]
Have you updated your cookies?

**Comment by ekvq** [comment]
Yep, cookies have been cleared and then re-imported a couple of times just to be sure

**Comment by AAndyProgram** [comment]
There is currently no verbose logging capability. Please post the profile URL you're trying to download.

**Comment by ekvq** [comment]
No worries! URL is `https://www.pornhub.com/model/nathanieladamsxxx/`

**Comment by AAndyProgram** [comment]
**Not confirmed**. Make sure that the [environment](https://github.com/AAndyProgram/SCrawler/wiki/Settings#environment), required for PornHub to work is set up correctly. PornHub [requires](https://github.com/AAndyProgram/SCrawler/wiki/Settings#pornhub-requirements) cookies, ffmpeg and curl.

Profile download completed successfully.
![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/1198d15f-8e53-4ce4-85da-27f54711f252)

**Comment by ekvq** [comment]
ok, so after looking into it more on my end, looks like Windows Security auto-blocked the executables for cURL and ffmpeg. my bad! Thanks for the help!!!

**Comment by AAndyProgram** [comment]
Oh yes. 😞 Antiviruses love to kill these programs. I recommend to add SCrawler, ffmpeg, curl, gallery-dl and yt-dlp to your antivirus exceptions.
