### ISSUE TITLE
[REQUEST] Plans for bypassing reddit's api restriction?

### ISSUE THREAD

**Issue by skiffkiddie** [AAndyProgram/SCrawler#157]
**Is your feature request related to a problem? Please describe.**
Used to use your app daily to scrape a large array of subreddits to archive media. I love it to death! Thanks so much for your hard work. Unfortunately SCrawler just cant do it currently, capping around 150 pieces of media per subreddit or user. 

**Describe the solution you'd like**
I know its absolutely no fault of your own or anything just wondering if you are planning on or are actively pursusing a work around for this going forward

**Describe alternatives you've considered**
Been working to find any scrapers / downloaders that can do it and today noticed that JDownlaoder2 has figured it out to some extent, can get max 1.3k per subreddit/user including imgur and redgif links.  Works pretty well, just figured i should note this in case they have something to borrow in the code lol

**Additional context**
Yeah not complaining or anything. Just a question! Thanks again for the work on this app. Its been so useful to me!

**Comment by AAndyProgram** [comment]
Delete cookies. Without cookies you will not encounter errors. The next version will add OAuth authorization for Reddit. However, this is not even required.

**Comment by AAndyProgram** [comment]
**Added**. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
