### ISSUE TITLE
Can't Delete user or move once added to collection[BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#16]
If a user is added to a collection by mistake, there seems to be no option to remove the user from the collection.

Additionally, when selecting a collection and using the "Delete user / collection" option, selecting the user from the list of users within the collection does not delete the user account (in fact, nothing appears to happen). The similar menu for editing a user within a collection seems to work fine.

I am using 2.0.0.4, 64x architecture.

**Comment by AAndyProgram** [comment]
>If a user is added to a collection by mistake, there seems to be no option to remove the user from the collection.

You can split the collection. Click the ```Delete``` button or right-click on the collection and select ```Delete user / collection```. In the dialog box, click ```Delete``` button. Then click ```No```, then ```Yes```. Then You can create the collection again.

>Additionally, when selecting a collection and using the "Delete user / collection" option, selecting the user from the list of users within the collection does not delete the user account (in fact, nothing appears to happen). The similar menu for editing a user within a collection seems to work fine.

You're right. I didn't add code to this function. I'll fix it in the next version.

**Comment by AAndyProgram** [comment]
I found a bug. I've added code to delete a user that is in the collection, but it's not declared correctly. This will be fixed in the next release. I will also add the ability to remove a user from the collection without deletion.

https://github.com/AAndyProgram/SCrawler/blob/19373ec4ba0f4bcffbe7dcddc3fe825fc5a4b3d8/SCrawler/API/UserDataBind.vb#L351

**Comment by AAndyProgram** [comment]
**Added**
- Ability to remove a user from the collection without deletion

**Fixed**
- Cannot delete a user that is in the collection.

**Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest)**
