### ISSUE TITLE
Twitter Cookie Error

### ISSUE THREAD

**Issue by YeetLover** [AAndyProgram/SCrawler#160]
When I try pasting the cookie 
![image](https://github.com/AAndyProgram/SCrawler/assets/142191076/619a4e80-7024-4a6b-8466-715d04fc62ba)
[ERROR_Log20230814_102232.txt](https://github.com/AAndyProgram/SCrawler/files/12331056/ERROR_Log20230814_102232.txt)
![image](https://github.com/AAndyProgram/SCrawler/assets/142191076/e1d4a2a5-44a1-4171-a9c9-129b3e536ee3)

**Comment by AAndyProgram** [comment]
Please read carefully [how to add cookies](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-set-up-cookies). There are two ways to add. If you can't add cookies from Chrome, try adding them using a plugin (I'm using [this one](https://www.editthiscookie.com/blog/2014/03/install-editthiscookie/)).
