### ISSUE TITLE
Fault Bucket type 0 when opening via Flash Drive

### ISSUE THREAD

**Issue by brmonaghan** [AAndyProgram/SCrawler#169]
**Describe the bug**
When resuming from sleep or hibernation and flash drive connected to SCrawler is removed when computer is asleep, the program crashes and writes to the event log this message:
Fault bucket 2293750621808340583, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 2273886318838712891

Problem signature:
P1: YouTubeDownloader.exe
P2: 2023.8.27.0
P3: fb09d24d
P4: clr.dll
P5: 4.8.9181.0
P6: 64b85478
P7: c0000006
P8: 000000000002436d
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a8e362a9-5bb5-4460-ac11-3d49c1c297b3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5138a435-1d6e-426f-8a75-03a634423ddc.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20230928_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a84fe4e9-7d5c-4e25-b334-71423a41af48.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b921f1e0-d4b1-45c4-ac5c-f5137f089bf1.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4647228b-e7bf-4907-a19c-f28c0e467e87.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8b7df2f9-510c-469f-a8a6-eaaca5b29dcb.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f3e64cac-a7a2-4a9a-a74b-59555c732d79.tmp.xml
\\?\C:\Users\cgeek\AppData\Local\Temp\WER.390d9310-431b-45b6-9adb-51c946c65eab.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.85651b14-2dfd-4f66-8158-fcdc4a1b14fc.tmp.hdmp
\\?\C:\Users\cgeek\AppData\Local\Temp\WER.c6af65ed-1aaa-43a9-9634-fa53b44348fb.tmp.WERDataCollectionStatus.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_YouTubeDownloade_d710ed75e29863ff2f9c20aea59450ad512019_1c19f363_cab_edf7a5d7-02c2-48dd-a6b7-7ad775951c4d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 99feda24-f509-4f4c-9474-4ecf430f3452
Report Status: 268435464
Hashed bucket: 8301be9698b03ce0afd50a09a837ae67
Cab Guid: bc95a0bb-f50d-4855-9f8e-778f36008a3b

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program SCrawler YouTube downloader because of this error.

Program: SCrawler YouTube downloader
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 0xC000026E
Disk type: 0x0
Faulting application name: YouTubeDownloader.exe, version: 2023.8.27.0, time stamp: 0xfb09d24d
Faulting module name: clr.dll, version: 4.8.9181.0, time stamp: 0x64b85478
Exception code: 0xc0000006
Fault offset: 0x000000000002436d
Faulting process id: 0x0x39A8
Faulting application start time: 0x0x1D9F39822907F21
Faulting application path: D:\Other Files\Folders\SCrawler\YouTubeDownloader.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 99feda24-f509-4f4c-9474-4ecf430f3452
Faulting package full name: 
Faulting package-relative application ID: 
**To Reproduce**
1. Put SCrawler on a USB stick or other external device.
2. Place computer into sleep or hibernation mode.
3. Wake computer from sleep or hibernation, inserting flash disk while computer boots up.
4. Program crashes immediately upon clicking close button or any other button. Task manager has to be utilized.

<details>
<summary>Log data</summary>
<pre>
Fault bucket 2293750621808340583, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 2273886318838712891

Problem signature:
P1: YouTubeDownloader.exe
P2: 2023.8.27.0
P3: fb09d24d
P4: clr.dll
P5: 4.8.9181.0
P6: 64b85478
P7: c0000006
P8: 000000000002436d
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a8e362a9-5bb5-4460-ac11-3d49c1c297b3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5138a435-1d6e-426f-8a75-03a634423ddc.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20230928_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a84fe4e9-7d5c-4e25-b334-71423a41af48.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b921f1e0-d4b1-45c4-ac5c-f5137f089bf1.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4647228b-e7bf-4907-a19c-f28c0e467e87.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8b7df2f9-510c-469f-a8a6-eaaca5b29dcb.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f3e64cac-a7a2-4a9a-a74b-59555c732d79.tmp.xml
\\?\C:\Users\cgeek\AppData\Local\Temp\WER.390d9310-431b-45b6-9adb-51c946c65eab.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.85651b14-2dfd-4f66-8158-fcdc4a1b14fc.tmp.hdmp
\\?\C:\Users\cgeek\AppData\Local\Temp\WER.c6af65ed-1aaa-43a9-9634-fa53b44348fb.tmp.WERDataCollectionStatus.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_YouTubeDownloade_d710ed75e29863ff2f9c20aea59450ad512019_1c19f363_cab_edf7a5d7-02c2-48dd-a6b7-7ad775951c4d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 99feda24-f509-4f4c-9474-4ecf430f3452
Report Status: 268435464
Hashed bucket: 8301be9698b03ce0afd50a09a837ae67
Cab Guid: bc95a0bb-f50d-4855-9f8e-778f36008a3b

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program SCrawler YouTube downloader because of this error.

Program: SCrawler YouTube downloader
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 0xC000026E
Disk type: 0x0
Faulting application name: YouTubeDownloader.exe, version: 2023.8.27.0, time stamp: 0xfb09d24d
Faulting module name: clr.dll, version: 4.8.9181.0, time stamp: 0x64b85478
Exception code: 0xc0000006
Fault offset: 0x000000000002436d
Faulting process id: 0x0x39A8
Faulting application start time: 0x0x1D9F39822907F21
Faulting application path: D:\Other Files\Folders\SCrawler\YouTubeDownloader.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 99feda24-f509-4f4c-9474-4ecf430f3452
Faulting package full name: 
Faulting package-relative application ID: 
</pre>
</details>

**Expected behavior**
Show a warning dialog when application is connected via flash drive and when computer is woken up from sleep or hibernate.

**Screenshots**
 
![image](https://github.com/AAndyProgram/SCrawler/assets/71337477/bbd89151-b396-479d-bd7c-9109ea4021bc)
![image](https://github.com/AAndyProgram/SCrawler/assets/71337477/386532f1-135b-43c3-845f-520f77a65a11)
![image](https://github.com/AAndyProgram/SCrawler/assets/71337477/d36ed54a-3c88-4cb9-8c27-771e14bba8e1)

**Release information:**

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**
 - OS: Windows 11 23H2 (22631)
 - Architecture: x64
 - Version: [e.g. 2023.3.5.0] 2023.8.27.0
 - NET.Framework version: 4.8
 - ffmpeg version (command `ffmpeg -version`): ffmpeg version 5.0-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
 - yt-dlp version (command `yt-dlp --version`): 
 - gallery-dl version (command `gallery-dl --version`):
 - cURL version (command `curl --version`):

**Additional context**

**Comment by AAndyProgram** [comment]
> When resuming from sleep or hibernation and flash drive connected to SCrawler is removed when computer is asleep, the program crashes and writes to the event log this message:

Excuse me, but the answer is in your question:

> Windows cannot access the file for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing.
