### ISSUE TITLE
Pull additional Instagram content [REQUEST]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#17]
Hi! I love this program so far, but I've noticed that on instagram it only pulls from a users _posts_ , when there's a lot more content that could be grabbed from there. I don't know how big of an addition this might be but I'd love if this worked with more than just the posts.

Specifically I would love to see the following added, perhaps in separate sub-folders within the users folder (like how videos are, by default):

1. Profile Pictures
2. Reels
3. Tagged Photos
4. Pinned Stories (ideally separated into additional subfolders by the name of the pin?)
5. Active Stories

I've attached an image of what areas on a profile I mean in case my terminology is wrong or unclear. Cheers!

![Untitled](https://user-images.githubusercontent.com/100350754/155515365-5b1a8701-cad4-40b1-82b1-0c97204258a1.png)

**Comment by AAndyProgram** [comment]
Thank you for your request. Actually, I already thought about some of them.

First of all, I want to say thank you for choosing my program. I'm glad you like it! :blush:

Instagram has really ugly API. In addition, Instagram is a very closed network. Without the official FaceBook authorization algorithm, it is very difficult to bypass their limits and restrictions. And it's a miracle that the developers left a few public functions, and this works with ```InstaHash```.

So, I'll try to answer step-by-step:
1. ```Profile Pictures``` - is it really that valuable?
2. ```Reels``` - Need to watch. I haven't looked at this yet.
3. ```Tagged Photos``` - unlikely
4. ```Pinned Stories (ideally separated into additional subfolders by the name of the pin?)``` - maybe later
5. ```Active Stories``` - Need to watch. I haven't looked at this yet. But unlikely.

Thank you for the detailed picture!

**Comment by AAndyProgram** [comment]
I have looked at the site and I have some remarks.

1. I can add this by I don't think it's valuable. To get a profile picture, the program will have to spend one more request (after 195 requests, the algorithm will work more slowly). In the case of such expensive requests, I don't think it makes sense to add a profile picture downloading.
2. I cannot find a profile with ```Reels``` in my feed. I need an example profile for more information. If you see a profile with ```Reels```, post it here.
3. I can add this. Instagram will require two additional parameters.
4. I researched the pinned stories. Instagram will require two additional parameters (same as ```Tagged Photos```) and the site's response is very heavy due to the large amount of data. But I can add stories.
5. Not found in any of the responses received. But isn't that the same as stories?

**Comment by TGJ64** [comment]
Thanks for your responsiveness! I'm not familiar with the kind of programming necessary for all this but I definitely get the impression instagram is a pain to work with (I found your program after the previous one I used stopped working for video posts, and yours is much more effective for my use-case) so I understand this being potentially more work than it's worth for you.

1. Agreed on the profile picture. It's a nice-to-have with the one-click convenience of your program but if it takes an entire request for one item then it's probably excessive, and if needed it can be gotten via other means.
2. Reels are weird, some people use them a lot and some not at all. They're a lower priority for me personally but I figured depending on how it's coded it would maybe be only a couple extra steps for you to add them. Here's a public profile with them though: https://www.instagram.com/ryangoslinguk/reels/
3. Would love tagged photos to be added if it seems reasonable!
4. I'd definitely love stories to be added, but I do have other programs that can grab them reasonably easily if it's a more complex task.
5. perhaps code-wise they show up the same. What I mean by "pinned" stories vs "active" stories is that active stories are posted and then stay visible for only 24 hours (and are then hidden to everyone but the user), whereas the pinned stories are stories that the user has pinned permanently to their profile and appear just above posts in little circular collections. So pinned stories used to be active stories, but I was envisioning the ability to click download and grab any stories that are presently active, as a separate thing from grabbing stories that have been pinned by the user.

**Comment by AAndyProgram** [comment]
Okay.

1. Canceled
2. Sorry but I don't see "reels" in this profile. In your picture (at number two), "reels" is a separate section. Profile which you posted does not have this. Or am I misunderstanding something?
3. It will be in the next version.
4. It will be in the next version. 
5. If I don't see them in the site's response, I can't develop this.

**Comment by AAndyProgram** [comment]
Hello. Sorry for the too long wait, but I will post a new release soon (in about two weeks). This will be a very big update. Really grand update.

**Comment by AAndyProgram** [comment]
Instagram tagged photos and stories added! 😊 

**Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest)**

**Comment by nemec** [comment]
@TGJ64 did post the right page for reels (I can see them, at least). Click back and forth between the "Reels" button and "Posts" in the UI section indicated in the picture. Tracking the Network tab it seems reels are pulled from this endpoint:

    POST https://i.instagram.com/api/v1/clips/user/

with a x-www-form-urlencoded encoded body

    target_user_id=<userid>&page_size=12&max_id=

Regarding 5,  you can see the response by clicking on the user's profile picture if they have a story (it will have a pink/orange circle surrounding the photo). The API call is

    https://i.instagram.com/api/v1/feed/user/<userid>/story/

Take this profile as an example (I just found it in Explore section, you can find more if story expires): https://www.instagram.com/destinationaire/

Thanks for the great tool :)

**Comment by AAndyProgram** [comment]
>@TGJ64 did post the right page for reels (I can see them, at least). 

I still don't see.

> https://www.instagram.com/destinationaire/

Sorry, but I only see videos, not reels.
![InstaVid](https://user-images.githubusercontent.com/88590076/158891587-55fa6665-b3b2-4f35-985f-dea33b029142.PNG)

>Regarding 5, you can see the response by clicking on the user's profile picture if they have a story (it will have a pink/orange circle surrounding the photo).

I will check it later.

**Comment by nemec** [comment]
Wow, that's wild. Instagram is playing favorites.

![Screenshot from 2022-03-17 16-30-54](https://user-images.githubusercontent.com/136378/158898395-bb8914fe-c4c1-4caf-99f1-cadd2e90a08b.png)

**Comment by AAndyProgram** [comment]
I don't know what to say 😞

**Comment by AAndyProgram** [comment]
@TGJ64, @nemec, due to the fact I can't see the reels, I can only suggest that you provide me with the request URL, the required authorization parameters and the JSON request response text.
Since this is sensitive information, I suggest that you write to me in the matrix: https://matrix.to/#/@andyprogram:matrix.org
Otherwise, I should close this issue till any changes.

**Comment by AAndyProgram** [comment]
@TGJ64, @nemec, finally, I saw the reels.

**This doesn't work:**
> @TGJ64 did post the right page for reels (I can see them, at least). Click back and forth between the "Reels" button and "Posts" in the UI section indicated in the picture. Tracking the Network tab it seems reels are pulled from this endpoint:
> 
> ```
> POST https://i.instagram.com/api/v1/clips/user/
> ```
> 
> with a x-www-form-urlencoded encoded body
> 
> ```
> target_user_id=<userid>&page_size=12&max_id=
> ```

I tried sending it (`target_user_id=<userid>&page_size=12&max_id=`) with a payload and a request URL but still got a 400 (Bad Request) error.

Any suggestions?

**Comment by nemec** [comment]
Here's the full request, including headers (data changed to protect my account 😁). Maybe you're missing some of the CSRF junk.

```
POST /api/v1/clips/user/ HTTP/2
Host: i.instagram.com
User-Agent: Mozilla/5.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-CSRFToken: abcde
X-Instagram-AJAX: abcde
X-IG-App-ID: 93
X-ASBD-ID: 123456789
X-IG-WWW-Claim: hmac.abcde
Content-Type: application/x-www-form-urlencoded
Content-Length: 45
Origin: https://www.instagram.com
Alt-Used: i.instagram.com
Connection: keep-alive
Referer: https://www.instagram.com/
Cookie: ig_did=abcde; ig_nrcb=1; csrftoken=abcde; fbm_12=base_domain=.instagram.com; ds_user_id=123456; sessionid=abcde; shbid="abcde"; shbts="abcde"; fbsr_12=abcde; rur="abcde"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers

target_user_id=123456&page_size=12&max_id=
```

**Comment by AAndyProgram** [comment]
`Host`, `TE` and `Alt-Used` were missing
Still getting the 400 error.
I'll try again later. Thank you for your help!

**Comment by AAndyProgram** [comment]
> POST /api/v1/clips/user/ HTTP/2

@nemec, you know, unfortunately, I didn't pay attention to the version of the protocol. If the protocol version is 2.0, I can't implement this because .Net.Framework only supports 1.0 and 1.1. 2.0 is only supported by .Net.Core. In this case, the only way to add it is to rewrite the code from .Net.Framework to .Net.Core. Or create a standalone CLI to receive these responses.

**Comment by nemec** [comment]
I doubt this is a feature restricted _only_ to HTTP/2, so that's probably not a journey worth embarking on. I would bet that whatever is missing can be done with the currently used framework.

**Comment by AAndyProgram** [comment]
Could you try this request with protocol version 1.0 or 1.1?

**Comment by AAndyProgram** [comment]
@nemec, have you tried this request again with protocol version 1.0 or 1.1?

**Comment by nemec** [comment]
Yes, I just tested with curl options `--http1.0` and `--http1.1` to force the protocol version and it returns the same JSON as HTTP/2.

**Comment by AAndyProgram** [comment]
Got it. I will try again. Thank you!

**Comment by nemec** [comment]
I don't know if it will help you at all, but I used Beyonce's page (user ID 247944034) to test 😄

https://www.instagram.com/beyonce/

**Comment by AAndyProgram** [comment]
Okay. I'll take note. 😄

**Comment by AAndyProgram** [comment]
Hello @nemec!
Still no. Do you know c# or vb.net? May you create a request (with HttpWebRequest) and test it? I have tested many times and always get 400 (Bad Request) error.

I have some more time to work on SCrawler. I'll post a new release soon and after that there won't be time to develop new functions for a while. If you want to help, then help. If not, I'll close this issue again until I have time again.

**Comment by AAndyProgram** [comment]
I tried to get a response with PowerShell and I got it. But still, when I try to write code with the same parameters in VisualBasic (VisualBasic  or c# doesn't matter) I always get a 400 (Bad Request) error.

This is a sample PowerShell code:
```PowerShell
$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
$session.Cookies.Add((New-Object System.Net.Cookie("ig_did", "abcde", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("ig_nrcb", "1", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("csrftoken", "abcde", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("ds_user_id", "123456", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("sessionid", "abcde", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("shbid", "shbid", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("shbts", "abcde", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("fbsr_12", "abcde", "/", ".instagram.com")))
$session.Cookies.Add((New-Object System.Net.Cookie("rur", "abcde", "/", ".instagram.com")))
$resp = Invoke-WebRequest -UseBasicParsing -Uri "https://i.instagram.com/api/v1/clips/user/" `
-Method "POST" `
-WebSession $session `
-Headers @{
"authority"="i.instagram.com"
  "method"="POST"
  "path"="/api/v1/clips/user/"
  "scheme"="https"
  "accept"="*/*"
  "accept-encoding"="gzip, deflate, br"
  "accept-language"="en-US,en;q=0.5"
  "dnt"="1"
  "origin"="https://www.instagram.com"
  "referer"="https://www.instagram.com/"
  "sec-ch-ua-mobile"="?0"
  "sec-ch-ua-platform"="`"Windows`""
  "sec-fetch-dest"="empty"
  "sec-fetch-mode"="cors"
  "sec-fetch-site"="same-site"
  "x-asbd-id"="123456789"
  "x-csrftoken"="abcde"
  "x-ig-app-id"="93"
  "x-ig-www-claim"="hmac.abcde"
  "x-instagram-ajax"="abcde"
} `
-ContentType "application/x-www-form-urlencoded" `
-Body "target_user_id=123456&page_size=12&max_id="
$resp.ToString()
```

**Comment by nemec** [comment]
Unfortunately, I don't know vb or winforms that well. All I can think of is to make very sure that HttpWebRequest does not add any headers by default that might make Instagram reject the request. Not sure what it would include, though.

**Comment by AAndyProgram** [comment]
Okay. Thanks anyway for trying to help! When I have time, I will probably return to this issue, but for now I close it again.

**Comment by AAndyProgram** [comment]
Hi guys! It looks that the reels are displayed in the user's timeline. I downloaded a profile with reels and the reels were downloaded from the timeline. I haven't checked all the reels, but it seems that the reels are downloading now.

In this case, I decided that this issue is completely closed. Thank you all for your help.

**Comment by AAndyProgram** [comment]
Added number 5! 🎉 
Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
