### ISSUE TITLE
Not able to fetch saved posts for Reddit acc

### ISSUE THREAD

**Issue by Sarah-xx** [AAndyProgram/SCrawler#171]
Hello, i have set up the app according to the given instructions. However, when i run the program to download my saved posts, it states "Reddit downloading starting" and return 0 images and videos.
I have checked the credentials multiple times but not able to locate the issue. 

![Screenshot 2023-10-23](https://github.com/AAndyProgram/SCrawler/assets/149017300/f73d8f40-386a-4616-8f47-975f0f2ea26e)
![Screenshot 2023-10-26 020943](https://github.com/AAndyProgram/SCrawler/assets/149017300/bec6a342-d7cf-460a-adf4-eea4b3611a3c)
![Screenshot 2023-10-26 021411](https://github.com/AAndyProgram/SCrawler/assets/149017300/83a3e4e6-1e18-4dae-abd9-41b3c47b4fc0)
![Screenshot 2023-10-26 021553](https://github.com/AAndyProgram/SCrawler/assets/149017300/da8fe910-a796-4297-b72d-b8f28e04e08a)

**Comment by AAndyProgram** [comment]
Uncheck `Use the token to download saved posts`

**Comment by Sarah-xx** [comment]
> Uncheck `Use the token to download saved posts`

Thank you so much. it worked.
Great software. Are you planning to add Facebook functionality in it? That'd be amazing coz there isn't a single one out there

**Comment by AAndyProgram** [comment]
You're welcome :-)

> Are you planning to add Facebook functionality in it?

Idk. Actually I had no such plans before. But in recent weeks I've started to think about it because there are several profiles that interest me. So **perhaps** this site will appear in future releases

**Comment by AAndyProgram** [comment]
Btw, join our Discord channel https://discord.gg/uFNUXvFFmg

**Comment by AAndyProgram** [comment]
Facebook added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
