### ISSUE TITLE
Auto Update Scrawler Batch File

### ISSUE THREAD

**Issue by Rootkit-** [AAndyProgram/SCrawler#175]
Not really a bug, just a unideal system of 
1. Launching scrawler
2. Having it notify you of update.
3. Starting update process 
4. Manually having to close Scrawler.
5. Update finishes
6. Manually starting Scrawler

```
@echo off
::Change this to your Scrawler Folder
CD /d C:\Tools\scrawler\

.\Updater\Updater.exe
.\SCrawler.exe

exit
```

**Comment by AAndyProgram** [comment]
I think it's not that hard to run SCrawler manually after the update 😊 

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by Rootkit-** [comment]
Very true. 
Its honestly nbd.
