### ISSUE TITLE
OnlyFans error 400 or 401 since latest update

### ISSUE THREAD

**Issue by Ubernoodles** [AAndyProgram/SCrawler#177]
Hello, I have been using Scrawler without issue for some time. I have found it to be a fantastic app. I use this exclusively for OnlyFans. Since the most recent update, I am unable to download any files. Instead I get error msg 400 or 401. I have reinstalled & replaced all information in the settings, but am still being told that my credentials have expired.
Is anyone else having this issue? I have installed OF Scraper & mp4decrypt.exe, pasting their paths to the OF settings, but this has not helped.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/discussions/176#discussioncomment-7964168

**Comment by AAndyProgram** [comment]
1. **To support downloading of DRM protected videos (OnlyFans), please update OF-Scraper to version [3.10](https://github.com/datawhores/OF-Scraper/releases/tag/3.10) (download `zip`, not `exe`).**
2. **If there is a `OFScraperConfigPattern.json` file in the SCrawler settings folder, replace the text of the file with [this text](https://github.com/AAndyProgram/SCrawler/blob/main/SCrawler/API/OnlyFans/OFScraperConfigPattern.json).**
3. **Set the value to `Dynamic rules` (in the site settings) = `https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json`.**

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by AAndyProgram** [comment]
**To support downloading of DRM protected videos (OnlyFans), please update OF-Scraper to version [3.10.7](https://github.com/datawhores/OF-Scraper/releases/tag/3.10.7) (download `zip`, not `exe`).**

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
