### ISSUE TITLE
Need help - Understanding reddit integration

### ISSUE THREAD

**Issue by Joly0** [AAndyProgram/SCrawler#178]
Hey, i am trying to get scrawler to download a reddit channel. I was able to add my own reddit account with the client id, secret and the token and that did work, but i have no idea, how i would add a subreddit. My plan here is to download all (if possible) images in a subreddit.
I thought, it cant be that hard, i click on channels, add the subreddit and click download, but as soon as i click on "Add" in the Channels window, i get the info "No user has been selected to add to the collection". I dont understand this and the wiki is not really helpful in my honest opinion :(

**Comment by AAndyProgram** [comment]
1. Click the `Add` button (main window)
2. Paste the channel URL into the `User URL` field
3. Click the `OK` button
4. Select this channel by clicking on it
5. Press `F5`

**Comment by AAndyProgram** [comment]
**Join our Discord server**: https://discord.gg/uFNUXvFFmg
