### ISSUE TITLE
Stories (user) downloading wrong aspect ratio for some users

### ISSUE THREAD

**Issue by S-rg-n** [AAndyProgram/SCrawler#179]
For some intagram users, their live stories, downloaded in the Stories (user) folder, often download in a square aspect ratio regardless of the actual aspect ratio of the posted image. This isn't changing the aspect ratio of the original image, it is just cropping it into a square.

An example user this happens with often is www.instagram.com/stories/quotedm3

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
