### ISSUE TITLE
JustForFans not downloading all media

### ISSUE THREAD

**Issue by NoPantsAvailable** [AAndyProgram/SCrawler#182]
I was testing out the JFF downloader before paying for a models subscription.
I managed to download 35 Videos, and 76 Images on the free tier.
I then cleared data & history, and paid for their subscription.

I was then able to download 37 Videos, and 88 Images on the paid tier.
According to JFF the model has 403 Videos, and 601 Images.

I've tried to force the download multiple times, and it just keeps saying "All Data Downloaded"
Nothing in the log, and no "Missing Posts" for that model

I'm running 2024.1.12.1 with Cookies, UserId, UserHash4, Accept, and UserAgent Headers set properly

I'm not sure what else I can provide. The model name won't be much help I don't think since you'd need a subscription.

**Comment by AAndyProgram** [comment]
Perhaps this model has many single paid posts?

**Join our Discord server**: https://discord.gg/uFNUXvFFmg


[![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/cc5139b5-d9e0-47c9-918f-89da8b4ce1a6)](https://discord.com/channels/1124032649682493462/1124281838056259614/1162495192499245107)
