### ISSUE TITLE
Instragram Partial Rip

### ISSUE THREAD

**Issue by yohuan94** [AAndyProgram/SCrawler#183]
Downloading an Instagram page partially works, seems to only download older photos and very few videos.
Much of the newer content was not downloaded. After having a look it only downloaded posts up until April 2023, everything after that was not downloaded.

https://www.instagram.com/_minniecharm/
Link for reference

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**
SCrawler v2024.1.18.0 (x64)
OS: Microsoft Windows 11 Pro (x64)
ffmpeg version: ffmpeg version 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
yt-dlp version: 2023.11.16
gallery-dl version: 1.26.4
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Comment by AAndyProgram** [comment]
How many photos and videos have you downloaded from this profile?

**Comment by AAndyProgram** [comment]
Downloaded 161 photos and 24 videos.
I find this profile fully downloaded.

Read this: https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-requirements

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by yohuan94** [comment]
Tried Again after latest version today, downloaded 161 photos and 24 videos compared to the 58 pics and 3 videos i got on the previous version. Thanks.

**Comment by AAndyProgram** [comment]
Nothing has changed in the timeline downloading algorithm
