### ISSUE TITLE
Not all instagram reels are being downloaded

### ISSUE THREAD

**Issue by S-rg-n** [AAndyProgram/SCrawler#184]
Only reels that are currently in the main timeline are being downloaded. Any reels that are in the actual Reels tab but not currently in the main timeline are not getting grabbed. 

For example, this account https://www.instagram.com/sh.0.ta has 1 reel in the timeline, which gets downloaded, and dozens in the Reels tab, which don't get downloaded.

**Comment by AAndyProgram** [comment]
Fixed (there is a new option in the site settings and in the user options). Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
