### ISSUE TITLE
[BUG] xhamster - not downloading anything

### ISSUE THREAD

**Issue by QbiX90** [AAndyProgram/SCrawler#186]
Hi. Using the actual Version, xhamster content is not downloaded/crawled at all.

**Comment by AAndyProgram** [comment]
Yeah, I know. Will be fixed in the next version (soon).

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
