### ISSUE TITLE
Videos download to _tmpCache then disappear

### ISSUE THREAD

**Issue by studioloft** [AAndyProgram/SCrawler#187]
Videos download to "_tmpCache" folder then disappear. I see them appear in small segments in the folder before it is deleted. Also I see these in the Info "Missing Posts" list.

Maybe I am missing something. Any help would be appreciated! Thank you,

Running the latest version 4/21/24

**Comment by AAndyProgram** [comment]
1. **[How to report a problem](https://github.com/AAndyProgram/SCrawler/blob/main/CONTRIBUTING.md#how-to-report-a-problem)**
2. `_tmpCache` as the title says, is a temporary cache. When the algorithm is completed, it's deleted. 😉 
3. If we're talking about JustForFan, I've notified users on our Discord server 
![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/2bbadef9-8d1a-432c-8f08-ba5b06779602)
4. **Join our Discord server**: https://discord.gg/uFNUXvFFmg
