### ISSUE TITLE
[BUG] INFO files (description,thumbnail,URL) not downloaded for some YouTube videos

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#188]
**DESCRIPTION of the ISSUE**
For some YouTube videos, the INFO files (_description,thumbnail,URL_) are not downloaded.
I have set the following options under the _INFO heading_ to **_TRUE_**:
- Create description files
- Create thumbnail files (music)
- Create thumbnail files (video)
- Create URL files

I have also set the videos to **_always be converted to MKV_**.

**You can REPRODUCE the issue**
by setting the same options to **_TRUE_** and downloading any or all of the following YouTube videos:

Below are some random videos about the Ukraine-Russian war, to demonstrate the issue.

**ATTENTION!** **ATTENTION!** **ATTENTION!**
**_If you are a sensitive person, do not watch/download these videos! They show war in all its ugliness, although YouTube approved (gore is blurred where required)._**

https://www.youtube.com/watch?v=W6CqRLN5WXQ&t=609s
https://www.youtube.com/watch?v=9id9i_BXmB8

For comparison, here are two with Cyrillic Title text that do download complete with INFO files:
https://www.youtube.com/watch?v=LGg7NSE2Ujw
https://www.youtube.com/watch?v=QeUMpneoHag

So, I guess it has nothing to do with the Cyrillic text of the Video Title? Or at least I don't think so, because other videos with Ukrainian text do download correctly, with all the INFO files included.

**Expected behavior**
I expect the video to be downloaded, along with the .TXT , .JPG and Url files.

**Release information:**

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**

YouTube Downloader v2024.4.26.0 (x64)
OS: Microsoft Windows 11 Pro (x64)
ffmpeg version: ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
yt-dlp version: 2024.04.09

**Comment by AAndyProgram** [comment]
Okay, I see. The first two videos contain a period (`.`) at the end of the file name. For unknown reasons, I see that yt-dlp isn't handling this character correctly. I'll fix this in the next version, but for now you should avoid using a period at the end of the file name.

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by JohnVKRDam** [comment]
Hi Andy,

Thanks for taking a look at this. I appreciate it 👍

They are not my videos, so I don't really have much control over not using a dot at the end of the Video Titles / Filenames 😉 But it is good to know that's what causing the issue.

Not sure if it is important, but what I see in the filenames of those downloaded videos with the issue, is that they all end with a # character. I take it that yt-dlp replaces the dot with the # automatically, when saving the file?

For instance:
FPV-ДРОН ОБЕРІГАЄ УКРАЇНСЬКИХ ШТУРМОВИКІВ. Підтримка піхоти FPV зі скидом від Батальйону К-2#.mkv
Підрозділ TERRA Вогневий наліт ЗСУ на опорний пункт ворога. Детальний розбір#.mkv
Підрозділ TERRA Фланг Бахмуту. FPV-дронами та скидами нищимо російських окупантів#.mkv
Окупанти згоріли у погребі. Авдіївський напрямок#.mkv
Авдіївський напрямок FPV дрони камікадзе проти російських танків Т90#.mkv

Again, not sure if that is important or not, but I thought I'd just report it 😊

Anyway, it is not a huge issue, because it is only on a limited number of videos. It's more of a small annoyance, because I now have to create those INFO files manually. Which is what I am temporarily doing now for such videos that fail.

Again, thank you for the swift reply. I will patiently await the next release 👍

Have a great day!
John

**Comment by AAndyProgram** [comment]
> They are not my videos, so I don't really have much control over not using a dot at the end of the Video Titles / Filenames 😉 But it is good to know that's what causing the issue.

You can manually check the file path to make sure it doesn't end with a period. And if so, then correct it here
https://github.com/AAndyProgram/SCrawler/wiki/YouTube-downloader#video
![tempsnip](https://github.com/AAndyProgram/SCrawler/assets/88590076/d61ef518-496d-49ae-bd9d-2b4cdec452a6)

Example:
Original file name
```
FPV-ДРОН ОБЕРІГАЄ УКРАЇНСЬКИХ ШТУРМОВИКІВ. Підтримка піхоти FPV зі скидом від Батальйону К-2..mkv
```
Replace with
```
FPV-ДРОН ОБЕРІГАЄ УКРАЇНСЬКИХ ШТУРМОВИКІВ. Підтримка піхоти FPV зі скидом від Батальйону К-2.mkv
```

> Not sure if it is important, but what I see in the filenames of those downloaded videos with the issue, is that they all end with a # character. I take it that yt-dlp replaces the dot with the # automatically, when saving the file?

Correct!

**Comment by JohnVKRDam** [comment]
Ooooh! You know, I never even realized checking the filename in the download context window. I just "blindly" click the download button, assuming I have already configured the default settings to my liking, and that is that 😂 I really should pay more attention to what I am actually doing LOL

Thank you pointing that (very helpful) option out for me 👍

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by JohnVKRDam** [comment]
Yes indeed! I have tested it and it works perfectly now 👍 Fantastic!!
Thank you so much for the quick fix!

Have a great weekend! 👍
