### ISSUE TITLE
[BUG] Twitter - not found on site

### ISSUE THREAD

**Issue by Disorbs** [AAndyProgram/SCrawler#189]
**Describe the bug**
twitter user not found/exist

**To Reproduce**
Downloaded new update and start the program and add a user from twitter and it shows up red not found, but i right click and open site and its working fine?

<details>
<summary>Log data</summary>
2024-05-07 11:02:01: User '[Twitter] - Wario64' not found on the site
</details>

**Expected behavior**
add twitter user and to download all videos and images

**Release information:**

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**
SCrawler v2024.5.4.0 (x64)
OS: Microsoft Windows 11 Pro (x64)
ffmpeg version: ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
yt-dlp version: 2024.04.09
gallery-dl version: 1.26.9
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Comment by AAndyProgram** [comment]
Not confirmed! Downloaded 100 first posts! Have you added cookies?

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
