### ISSUE TITLE
[BUG] Network Location Ignored

### ISSUE THREAD

**Issue by oushima** [AAndyProgram/SCrawler#190]
**Describe the bug:**
Hello, when I use `192.168.2.141` as my download path, the program ignores it and creates its own.
`\\MySynologyNas\downloads\data\` also doesn't work, it gets added, but it doesn't download there.
I also tried a shortcut but that also doesn't work. (I just select it, I didn't write anything manually, it auto generates the path)

**To Reproduce:**
Select a network location as path and then try to download something.

**Release information:**
SCrawler_2024.5.4_x64

**Comment by AAndyProgram** [comment]
**Not confirmed!**
Tested:
```
\\192.168.1.68\test\
```
Mounted folder (`This PC` - `Map network drive`)
```
Z:\test\
```

Everything downloaded fine (both)!

**You might need to configure the correct access permissions (read & write)!**

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by oushima** [comment]
Ah, I already figured it out.

I had to delet the paths from the Profiles such as Reddit, Twitter, Instagram, Threads, etc., so it could take the global path defined in Settings.

Thank you for your swift reply and help. It's fixed now.

I did not use a mounted folder in This PC -> Map network drive.

I created a desktop shortcut pointing to my NAS instead, but it works the same!
