### ISSUE TITLE
RedGifs keeps downloading random videos unrelated to selected profile.

### ISSUE THREAD

**Issue by lovesnakeden** [AAndyProgram/SCrawler#191]
Hello.
I have been having this bug for, like, a few weeks now.
I have selected only 1 RedGifs profile (pixie2222) in SCrawler that doesn't post that much, yet SCrawler keeps downloading GBs of random images and videos daily from other RedGifs profiles that I don't even know. lol
I have completely deleted the SCrawler folder or directory, downloaded the latest one, and unpacked it, yet the problem still persists.

SCrawler v2024.5.4.0 (x64)
OS: Microsoft Windows 11 Pro (x64)
ffmpeg version: ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
yt-dlp version: 2024.04.09
gallery-dl version: 1.26.9
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Comment by AAndyProgram** [comment]
I saw your report in bug reports and tested this profile. Not confirmed. I completely downloaded this profile and the next time I try, nothing is downloaded because of no new posts.

Please attach the file `User_RedGifs_pixie2222.xml` from the user setting folder

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/3e557d52-48d7-4da7-918b-0b6cb3139de6)

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by lovesnakeden** [comment]
[User_RedGifs_pixie2222.zip](https://github.com/AAndyProgram/SCrawler/files/15279791/User_RedGifs_pixie2222.zip)
Thank you.
It happens randomly throughout the day. You have to wait at least 1 day, or better, a few days.
I have attached that .xml file in zip archive.

**Comment by AAndyProgram** [comment]
Okay, the file looks good. I'll add this profile again. I'll try to download it in a couple of days. But I've never seen this kind of behavior on RedGifs (I also have a couple profiles in SCrawler).

**Comment by AAndyProgram** [comment]
Btw, if you added cookies, delete them. They aren't needed.

**Comment by lovesnakeden** [comment]
> Okay, the file looks good. I'll add this profile again. I'll try to download it in a couple of days. But I've never seen this kind of behavior on RedGifs (I also have a couple profiles in SCrawler).

Yeah me neither. lol It started happening like a week or two ago.
I have been using SCrawler since November 2023 without any issues.
I have Automation on aka Scheduler. I attached a pic of my settings.
![auto](https://github.com/AAndyProgram/SCrawler/assets/169440317/424b4c22-6711-4b86-b6d9-dad59d01466f)

> Btw, if you added cookies, delete them. They aren't needed.

It says 0 cookies. I have added only token an user agent in RedGifs settings.

> Does the same issue occur on other RedGifs profiles?

I have mostly used SCrawler for Reddit profiles, some Twitter and few RedGifs.
Nope. I haven't noticed something like that.
(Or maybe I haven't looked in other RedGifs folders, but I can someday, just to compare if it was downloading exactly that user's videos and pictures, not some random ones)

**Comment by AAndyProgram** [comment]
> I have added only token an user agent in RedGifs settings.

**You shouldn't set it manually!**
https://github.com/AAndyProgram/SCrawler/wiki/Settings#redgifs-requirements
![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/c5d7f3ee-4c9c-4989-8e5e-bfcc900aeb0a)


> I have Automation on aka Scheduler. I attached a pic of my settings.

**Timer value = 1?!** Why do you download this so often? Maybe the problem is here?

**Comment by lovesnakeden** [comment]
> You shouldn't set it manually!

Oh gosh! Now I am cursed! lmao
Jokes aside. I remember reading on the SCrawler wiki how to setup a RedGifs token because it was _required_, but I guess it's an older setting from 2023 that maybe doesn't work in 2024? lol
Should I try to delete it now and see if it's because of that old token that I pasted from my browser developer tools?
![image](https://github.com/AAndyProgram/SCrawler/assets/169440317/ae61abf5-8b49-4b24-83f6-29169eaf6945)

> Timer value = 1?! Why do you download this so often? Maybe the problem is here?

Nah. Lol, for the lulz, maybe? :") To be honest, I've been using SCrawler since November 2023 with exactly the same settings, just updated to a new version once a month. To tell you the truth, I have been checking _multiple_ times per day that user folder, and I haven't seen any random GB's of videos or pictures, only the user ones. It started happening a week or two ago.
Also, it would be _very_ cool if VSCO was supported. I remember reading somewhere that it's possible to request a new site...
Anyways. Thank you very much for this program, Andy; it makes a lot of things _much_ more easier.
I'll catch you later. I am not in a hurry; I just wanted to help you fix that bug. :")
Looking forward.

**Comment by AAndyProgram** [comment]
> Should I try to delete it now and see if it's because of that old token that I pasted from my browser developer tools?

Just click on the curved arrows to refresh the token. Then click `OK`

> I have been checking multiple times per day

Do you know about ['Feed'](https://github.com/AAndyProgram/SCrawler/wiki#feed)?

**Comment by lovesnakeden** [comment]
> Just click on the curved arrows to refresh the token. Then click OK

Got it. Done.

> Do you know about 'Feed'?

I have seen it, but I haven't used this function. I will check it out.
I check the profile manually via Windows Explorer, and that's how I discovered those random unrelated videos/pictures.

**Comment by lovesnakeden** [comment]
![image](https://github.com/AAndyProgram/SCrawler/assets/169440317/97cd551f-efc6-4538-a5c7-7306cc37a034)
lol It's still happening.
I noticed it happens around 2PM every day. You can see in attached pic that it downloaded 83 new vids lmao (106 including the user ones), yet the user haven't uploaded anything since April 29th.
Should I try to delete SCrawler directory, unpack the clean one and don't add anything to RedGifs settings?
(last time I added the token myself)

**Comment by AAndyProgram** [comment]
Tried it twice today. Nothing. I'll try tomorrow

> don't add anything to RedGifs settings?

**You don't need to configure RedGifs settings at all!**

> Should I try to delete SCrawler directory, unpack the clean one and don't add anything to RedGifs settings?

1. Close SCrawler.
2. Delete the following files from the SCrawler settings folder.
3. Open SCrawler

```
Responser_RedGifs.xml
Responser_RedGifs_Cookies.xml (if it exists)
Responser_RedGifs_Settings.xml
```

**Comment by AAndyProgram** [comment]
Updated RedGifs requirements chapter
https://github.com/AAndyProgram/SCrawler/wiki/Settings#redgifs-requirements

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/d8ecb8d0-b592-42cc-83f1-9f5e6af2be05)

**Comment by lovesnakeden** [comment]
> Tried it twice today. Nothing. I'll try tomorrow

Thank you again. I am not in a hurry anyway. :")

> You don't need to configure RedGifs settings at all!

Oh cool. I will not touch it ever again. 

> 1. Close SCrawler.
> 2. Delete the following files from the SCrawler settings folder.
> 3. Open SCrawler

Done. Let's see what happens next.

**Comment by lovesnakeden** [comment]
lmao Again wtf! Almost at the same time every day! lol
Could this be some kind of spyware/virus?
I can run IObit Advanced SystemCare Pro deep scan, Razer Cortex system clean and Malwarebytes scan.
![image](https://github.com/AAndyProgram/SCrawler/assets/169440317/71a5a8c2-d285-4d39-bf5a-0200abba066c)

**Comment by AAndyProgram** [comment]
Sorry. **Can't confirm.** Two days and nothing! Nothing has been downloaded since the first download...
![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/adedee2a-232c-4c31-85c0-bc68d307a7eb)
