### ISSUE TITLE
[REQUEST] YouTube Downloader : Add YouTube video UPLOAD DATE to the INFO > Description .txt-file

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#192]
**_DESCRIPTION_**
**YouTube Downloader**
Is it possible to add the _UPLOAD DATE_ of a downloaded YouTube video to the INFO > Description .txt-file?

Currently, the only date & time we have is that of when the video was downloaded (file creation date & time). Which is also good information, of course, because it allows me to check & see when I downloaded the video.
But I often download videos from a long time ago, and it would be very helpful if the date of when the video was actually uploaded to YouTube was recorded in the INFO .txt-file, alongside the description of the video.

**_SOLUTION_**
The **_upload date_** would be at the top of the .txt-file, BEFORE the video description. The same order as on YouTube, when you click the **_MORE_** button on the video description.

**Comment by AAndyProgram** [comment]
Okay. Will be added in the next version.

**Comment by AAndyProgram** [comment]
Added (enabled by default). Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Comment by JohnVKRDam** [comment]
Wow! That was so fast! Amazing!
Thank you so much for the quick fix and update! 👍👍👍
