### ISSUE TITLE
[REQUEST] Option in Settings to add the YouTube video UPLOAD DATE to the file name ( between square brackets [...] )

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#194]
[REQUEST]
Would it be possible to add an option in the Settings, under the header INFO, to add the YouTube video UPLOAD DATE to the file name?

It would help in more easily saving videos that have the same name. unfortunately, I have quite a lot that have the same name (lazy YouTubers...).

The format would be like this:
file name [UPLOAD DATE].mkv

The date between square brackets, to easily identify the ADDED date (because sometimes there's also a date in the file name).

**Comment by AAndyProgram** [comment]
Good idea. Will be added to the next version.

**Comment by AAndyProgram** [comment]
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
