### ISSUE TITLE
[REQUEST] YouTube Downloader: Add an option to the Settings to skip the "Download Video" options window after adding a Url to download

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#195]
Is it possible to add an option to the Settings of the YouTube Downloader that allows us to skip the DOWNLOAD VIDEO window that appears when you add a Url to download?

That way you don't always have to click the DOWNLOAD button in that window to accept your choices, before it start downloading the video.

With that new option (maybe called something like "Skip Download Video options window, accepting the default settings") set to TRUE, the video would immediately start downloading after you ADD the Url to the list. The download should then just happen, without having to confirm them, with the settings as they are in the Download Video window.

**Comment by AAndyProgram** [comment]
Okay. I'll think about it.

**Comment by AAndyProgram** [comment]
**This will not be added anytime soon, sorry.** I don't see a need for this option for most end users. If you want to add a list of URLs, click the `Add URL array` button. You'll still see a form, but a different one, where the URLs you added will be in a list and you can simply click the `Download` button.

https://github.com/AAndyProgram/SCrawler/wiki/YouTube-downloader#playlist
![](https://raw.githubusercontent.com/AAndyProgram/SCrawler/main/ProgramScreenshots/AppYouTubePlaylist.png)

*However I've added your issue to my list of potential tasks, and perhaps someday your request will be implemented.* 😉
