### ISSUE TITLE
[NSFW] Not sure if this is grabbing all data from Reddit users - Follow up

### ISSUE THREAD

**Issue by BluesFanUK** [AAndyProgram/SCrawler#197]
The last one was closed without being resolved, so this appears to be a bug.
https://github.com/AAndyProgram/SCrawler/issues/196

Here is another one that didn't work:
[https://www.reddit.com/user/evergreenfairy96](url)

She's got loads of videos too, here's one:
[https://www.reddit.com/r/VerifiedFeet/comments/17b0mrh/what_caught_your_eye_first/](url)

All images, **no** **videos**, downloaded several months ago, I've tried to re-download and just get the 'all data downloaded' message. I've checked the user data log and there's no mention of ID 17b0mrh or anything with .mp4.

What's causing the issue? I've got loads of users downloaded and doing a random check there are other users with videos downloaded, so i'm confused why this program is refusing to pick them up for some users and not others? Please advise.

**Comment by BluesFanUK** [comment]
![Reddit](https://github.com/AAndyProgram/SCrawler/assets/126352869/d22ca317-6602-4f6a-949f-31dc7a019200)
Here are my settings.

**Comment by AAndyProgram** [comment]
Check the `Use M3U8` checkbox in Reddit settings

**Comment by BluesFanUK** [comment]
> Check the `Use M3U8` checkbox in Reddit settings

Tried that and it still isn't working, any other suggestions?

**Comment by BluesFanUK** [comment]
> Check the `Use M3U8` checkbox in Reddit settings

I've cleared the whole settings folder for one of the users (copied the original data over first), then ran the download again through the system, and it's picked up 1 video, not the rest, there's definitely a bug here. It's also missing a shit ton of images. 

https://www.reddit.com/user/kg_soles/

These didn't download (at the very least)

- https://packaged-media.redd.it/95hebfwwxfn91/pb/m2-res_1080p.mp4?m=DASHPlaylist.mpd&v=1&e=1718056800&s=9f8aa28d031e679d67868c299e01fb490dc64973
- https://v.redd.it/q5obw0lo8kh91/HLS_576.m3u8
- https://v.redd.it/anl76bn795m91/HLS_576.m3u8

There's clearly an issue here.

**Comment by BluesFanUK** [comment]
I've deleted the entire user and started again.... same issue, downloads 70 odd images, no videos at all. This is a bug, please reopen the thread.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/issues/198#issuecomment-2159327103
