### ISSUE TITLE
All Reddit users are not being downloaded correctly. Bugged and can no longer download, bearer token issue???

### ISSUE THREAD

**Issue by BluesFanUK** [AAndyProgram/SCrawler#198]
I'm not sure why these are being closed without a resolution.

This whole profile and every other one i've got is NOT downloading everything, i'm using this one as an example as it's got a smaller sample to look at instead of people who constantly flood other channels with their content.

```
USER
https://www.reddit.com/user/kg_soles/

EXAMPLES NOT DOWNLOADING
https://packaged-media.redd.it/95hebfwwxfn91/pb/m2-res_1080p.mp4?m=DASHPlaylist.mpd&v=1&e=1718056800&s=9f8aa28d031e679d67868c299e01fb490dc64973
https://v.redd.it/q5obw0lo8kh91/HLS_576.m3u8
https://v.redd.it/anl76bn795m91/HLS_576.m3u8
There's clearly an issue here.

These images didn't download either:
https://www.reddit.com/r/VIPFeet/comments/wmjl8p/lets_stay_in/

```
m3u8 is now ticked as previously advised, and I've done the following:

**Test 1**
Deleted the users settings
**Outcome**
Click Download all, only one video downloaded

**Test 2**
Delete the user entirely and start from scratch
**Outcome**
Same download as previously but no videos

**Test 3**
Re-add cookies (Cookie-Editor > Export as Netscape
**Outcome**
Five videos download, still missing some and lots of images from within the year

**Test 4**
Deleted the bearer token and found it on reddit again (not the easiest guide to follow here).
**Outcome**
Can no longer download anything, just a profilebanner and opening the settings folder - Log says [502] Reddit is currently unavailable, I'm assuming this is reddit rate limiting me. My whole history going back months has a load of errors too.

**Summary**
The program seems to be very hit and miss on what it downloads, it often misses images and is extremely erratic with video downloads, the user in question here has well under 1,000 posts. What's causing the issue here?

**Comment by AAndyProgram** [comment]
1. Stop opening new issues. You can continue the previous one, even if it has closed.
2. Don't enter the token manually! 
![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/fb5071a4-fc5d-4925-b528-451ca47b97d9)

**Comment by AAndyProgram** [comment]
I updated the Reddit wiki chapter
