### ISSUE TITLE
[REQUEST] Support for downloading archive posts in Onlyfans

### ISSUE THREAD

**Issue by myacct123** [AAndyProgram/SCrawler#199]
**Is your feature request related to a problem? Please describe.**
Currently, SCrawler doesn't download archive posts from Onlyfans but this is possible (OF-DL does it)
**Describe the solution you'd like**
Option for downloading archive posts from OF

**Describe alternatives you've considered**
n/a

**Additional context**
Thank you for anyone interested!

**Comment by AAndyProgram** [comment]
I need access to an account with a profile with archived posts
https://github.com/AAndyProgram/SCrawler/wiki/Settings#paid-sites-partial-support

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
