### ISSUE TITLE
Third party (Imgur gyazo etc.) gallery/image link support

### ISSUE THREAD

**Issue by ShiroUwUs7** [AAndyProgram/SCrawler#2]
allow imgur / other third party link support to grab images/videos/gifs hosted from imgur also as it skips those, for twitter and reddit and most people use imgur to upload!

**Comment by AAndyProgram** [comment]
Sorry, I need to sort this out. The program has downloaded imgur media in the past, but a few weeks ago I updated the parsing algo and something may have gone wrong.

**Comment by ShiroUwUs7** [comment]
All good, mind replying here when it gets fixed? also do you know if a CLI
download all would be able to be implemented for scripting purposes?

**Comment by AAndyProgram** [comment]
I don't know about the time. I need a user profile with imgur content to fix it. When I see it, I'll fix it.
About a CLI: I will not implement CLI functionality. I don't like CLI, so I made this GUI program. In additional, the implementing CLI functionality also takes time.

**Comment by ShiroUwUs7** [comment]
> I need a user profile with imgur content to fix it.

I have one. Can use [https://www.reddit.com/user/EldritchSlut/](https://www.reddit.com/user/EldritchSlut/)
not my profile but a lot of imgur links.

**Comment by AAndyProgram** [comment]
I see. Thank you. In the coming days I will try to fix it.

**Comment by AAndyProgram** [comment]
Imgur support fixed
https://github.com/AAndyProgram/SCrawler/releases/tag/1.0.0.4
