### ISSUE TITLE
Windows Defender sees Scrawler.exe as a trojan

### ISSUE THREAD

**Issue by LordEng1ish** [AAndyProgram/SCrawler#200]
**Describe the bug**
Windows Defender sees Scrawler.exe as a trojan. 
Trojan:Win32/Bearfoos.A!ml

**To Reproduce**
1. Unzip the scrawler zip files
2. Windows defender tells you it found a trojan, Trojan:Win32/Bearfoos.A!ml

**Expected behavior**
Windows defender finds no trojans. 

**Screenshots**
![trojan](https://github.com/AAndyProgram/SCrawler/assets/94722153/3695b561-c3b5-47ac-b71e-0a540895e35b)

**Release information:**
SCrawler v2024.6.10.0 (x64)
OS: Microsoft Windows 10 Home (x64)
ffmpeg version: ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
yt-dlp version: 2024.05.27
gallery-dl version: 1.27.0
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Additional context**
Reddit comments tell me ".ml" means machine learning and is often a false positive. I've used past versions of scrawler without any problem. I trust scrawler. Malwarebytes did not detect scrawler as anything. 

I believe unrelated, malwarebytes found some other junk in my chrome data folders, which I believe would be my fault from other sources. 
![malware](https://github.com/AAndyProgram/SCrawler/assets/94722153/703927fd-dc4a-4187-98bb-c96d315bc684)

**Comment by AAndyProgram** [comment]
SCrawler doesn't contain any viruses at all. All code is posted here (on GitHub). You can review it. I have nothing to hide. SCrawler just downloads pictures and videos. That's all.

> I trust scrawler. Malwarebytes did not detect scrawler as anything.

If you trust SCrawler, you should just add it to the antivirus exceptions, as I did. Sometimes antiviruses identify SCawler as a virus. This is usually related to the number of files being edited (users' settings files) and the number of files being downloaded. In this case, the antivirus can also remove these files, which will damage users' settings.
