### ISSUE TITLE
[BUG] YT Downloader is unable to add and download age restricted videos

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#205]
**Describe the bug**
On the latest YT Downloader version (just updated from within YT Downloader a moment ago):
YT Downloader is unable to add and download age restricted videos. Even when I do not see the age restriction message before playing the video.

**To Reproduce**
- Use this Url (age restricted video): https://www.youtube.com/watch?v=gW2X3Murgns
- Then ADD (INS) it to the download list in YT Downloader
- It will only briefly show the small form with the message "Parsing data" (**see screen shot below**), then it will stop processing (without any further messages) and return control to the main form.

**The LOG contains no data**

**Expected behavior**
To download the age restricted video

**Screenshots**
![image](https://github.com/user-attachments/assets/59f7bec4-4367-436c-88e4-12dd318746c1)

**Release information:**
 - OS: **Windows 11**
 - ffmpeg version (command `ffmpeg -version`): **5.1.2-full_build**
 - yt-dlp version (command `yt-dlp --version`): **2024.08.01**
 - gallery-dl version (command `gallery-dl --version`): **1.27.1**
 - cURL version (command `curl --version`): **curl 8.8.0 (Windows) libcurl/8.8.0 Schannel zlib/1.3 WinIDN | Release-Date: 2024-05-22**

**Comment by AAndyProgram** [comment]
To download 'age restricted' videos, you need to add cookies (`Settings` - `Environment` - `Cookies`).
How to add cookies: https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-set-up-cookies
After that, click on the `Add (Ins)` button and in the submenu, click the same button (`Add (Ins)`) with the `Control` key. Or just press `Ctrl+Insert`.

**Comment by AAndyProgram** [comment]
I tried to download the video you posted but I couldn't even with cookies. I reviewed the code and saw a bug. I added the use of cookies for data parsing, but completely forgot to add it for data downloading. Sorry.

**Fixed**. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
