### ISSUE TITLE
[BUG] Can't change data path

### ISSUE THREAD

**Issue by WanHaes** [AAndyProgram/SCrawler#206]
**Describe the bug**
Data Path in SCrawler settings cannot be changed due to an error.

**To Reproduce**
1. Original data path: D:\Portable\SCrawler\Data
2. Wanted data path: D:\DATABASES\SCrawler
3. Choose new path in settings
4. Click OK button in settings window
5. Pop up will appear saying that "global path changed" and asking to confirm the change, click Process
6. Error message uppears and actual data path doesn't change (data is still downloaded in the original data path)

<details>
<summary>Log data</summary>
<pre>
No log data
</pre>
</details>

**Expected behavior**
Data path is changed successfully

**Screenshots**
![2024-08-31_17-39-49](https://github.com/user-attachments/assets/e313cc8e-2f16-4ab9-a075-af24b3af7233)

**Release information:**

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**
SCrawler v2024.8.10.0 (x64)
OS: Майкрософт Windows 10 Pro (x64)
ffmpeg version: ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
yt-dlp version: 2024.08.06
gallery-dl version: 1.27.2
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Additional context**
-/-

**Comment by WanHaes** [comment]
Hm, okay, path is updated in Settings.xml, new path is set in MOST individual settings of sites. Path did not change in Instagram and Reddit settings.

**Comment by WanHaes** [comment]
Next attempt to change global path → restarted the app → path didn't change in any of the individual settings

**Comment by AAndyProgram** [comment]
**Confirmed.** I'll try to fix it in a couple of months.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
