### ISSUE TITLE
[REQUEST] Make the user cover images display/fit correctly

### ISSUE THREAD

**Issue by WanHaes** [AAndyProgram/SCrawler#207]
**Is your feature request related to a problem? Please describe.**
Cover images of users are stretched to a fixed aspect ratio. This is visually unpleasant.

**Describe the solution you'd like**
Cover images have their original aspect ratio

**Describe alternatives you've considered**
Make an option to manually reposition an image within a fixed canvas to fit it correctly. Or make it fit automatically (with cropping)

**Additional context**
Actually, image fits the fixed canvas just when you set it, then it stretches after restart
![2024-08-31_19-14-41](https://github.com/user-attachments/assets/cf0ff414-617b-4be0-a53e-4bf719a9709d)       ![2024-08-31_19-16-00](https://github.com/user-attachments/assets/1bc4df9b-4dbf-4670-9116-37d90d790b07)

> image fits the fixed canvas just when you set it

This cause a little visual bug when a new image is layered on top of an old one
![2024-08-31_20-02-11](https://github.com/user-attachments/assets/6a5df2e5-d2d6-4704-b4ee-2787a5c8e2d9)

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by WanHaes** [comment]
It still stretches

**Comment by AAndyProgram** [comment]
Well, now the images shouldn't overlap. But the cropped image won't be added. The native class doesn't have any properties for scaling (like `PictureBoxSizeMode`), and I don't want to deal with redrawing. If you post a code (in `vb.net` or `c#`) to do this, I'll try to add.

**Comment by WanHaes** [comment]
> Well, now the images shouldn't overlap.

Nah, they still overlap if new cover image is narrower than canvas. It doesn't stretch immediately.

> The native class doesn't have any properties for scaling (like PictureBoxSizeMode), and I don't want to deal with redrawing.

Well, okay then :(

> If you post a code (in vb.net or c#) to do this, I'll try to add.

I don't know coding, otherwise I'd probably try to do it
