### ISSUE TITLE
Not downloading videos from justforfans

### ISSUE THREAD

**Issue by Darkpte** [AAndyProgram/SCrawler#208]
I tried to use SCrawler to download a justforfans profile. it worked great but downloaded photos only but no videos. I made sure to check download videos in the options menu but no good. any help please.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/blob/main/FAQ.md#sites-questions

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
