### ISSUE TITLE
Instagram saved post download issue

### ISSUE THREAD

**Issue by kasahiti** [AAndyProgram/SCrawler#209]
**Describe the bug**
When starting the download of instagram saved post by clicking on the bookmark icon, only 20 first posts are being downloaded.

**To Reproduce**
1. Click on bookmark icon
2. Click on "Play" icon inside instagram line
3. Wait for download
4. No error, but only 20 first posts are downloaded

**Expected behavior**
More posts should be downloaded instead of just 20.

**Screenshots**
N/A

**Release information:**

**Please complete the following information or replace the following text with data copied from SCrawler (click the top right info button in the main window, then the `Environment` button, then the `Copy` button, and paste the copied text here).**
 - OS: Windows 11
 - Architecture: x64
 - Version: 2024.9.2.0
 - NET.Framework version: 
 - ffmpeg version (command `ffmpeg -version`): 5.1.2
 - yt-dlp version (command `yt-dlp --version`): 2024.08.06
 - gallery-dl version (command `gallery-dl --version`): 1.27.3
 - cURL version (command `curl --version`): 8.8.0

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/blob/main/FAQ.md#sites-questions
