### ISSUE TITLE
Doesn't work for Twitter?

### ISSUE THREAD

**Issue by LawrenceDinh** [AAndyProgram/SCrawler#21]
Not downloading anything even though I pasted in the Token and Authorization.

**Comment by LawrenceDinh** [comment]
It just says all data downloaded and nothing happens and downloads a blank XML file...

**Comment by AAndyProgram** [comment]
This also require a cookie

**Comment by AAndyProgram** [comment]
Due to the fact that I have not received further answers from you, I consider this issue closed.
