### ISSUE TITLE
[BUG] [YT Downloader] Can't download YT video, even when changing the file name

### ISSUE THREAD

**Issue by JohnVKRDam** [AAndyProgram/SCrawler#211]
I cannot download this video, no matter what I do:
https://www.youtube.com/watch?v=he5mlEYWCaY

The title is:
**_Russia Had Their WORST Week of the War! Over 10,000 Casualties!_**

I have tried changing the file name, and the resolution, but it just won't download.
Other videos download without problem.

1. Copy the Video Url
2. Click **Add (INS)** in the YT Downloader
3. It shows the small "Parsing program" form
4. Then it displays the "Download video" form, where I can change the name
5. I change the file name and press the Download button
6. It immediately shows the video in the list as downloaded (within a second), but nothing is actually downloaded
7. There are no errors, nor is there a LOG

I have the application settings to download (convert to) MKV and in the highest possible resolution (my settings is 2160p).

As I've noted, other videos download without issue. There is seemingly nothing special or different about this video. I have download content from this channel before, on a regular basis, in fact.

**Release information:**
 - OS: **Windows 11 Pro [23H2] [Version 10.0.22631.4317]**
 - Architecture: **x64**
 - Version: **v2024.9.2.0 (x64)**
 - NET.Framework version: 
 - ffmpeg version (command `ffmpeg -version`): **5.1.2**
 - yt-dlp version (command `yt-dlp --version`): **2024.08.06**
 - gallery-dl version (command `gallery-dl --version`): **1.27.3**
 - cURL version (command `curl --version`): **8.9.1**

**Comment by AAndyProgram** [comment]
**Confirmed.** Something is wrong when downloading via `m3u8` protocol. Will be fixed in the next version. For now, you should avoid downloading via `m3u8` protocol in high resolutions. Choose `http`/`https`. I can download this video in 1080.

![image](https://github.com/user-attachments/assets/f80c2bee-7f65-4767-a075-e8d3e3908131)

**Comment by JohnVKRDam** [comment]
Hi Andy,

Thanks for the quick response!

I actually tried downloading in 1080p, but it also didn't work. But now I see that I chose the m3u8 1080p option. The https option does indeed work, as you say  😊  Because the 1080p didn't work for me, I didn't even try the https option. Obviously I should have, though  😉  haha

It's not urgent  😊  I now have the 1080p option as a backup, and I also still have Internet Download Manager installed. It can download the MKV's, but without all the very nice bells and whistles (Url, Txt file, subtitles, and thumbnail) of YT Downloader  😉

Thanks again! 👍

![2024-10-23_161620](https://github.com/user-attachments/assets/b4ec0a98-16d5-42a8-a496-142288623562)

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

----

Don't use the `m3u8` protocol. You can set the preferred protocol in the settings (`Protocol`). For UHD, added the ability to download `webm` with conversion to more native formats. Enjoy! 😊 

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by JohnVKRDam** [comment]
Awesome!! It works great now 👍 Thank you so much!

**Comment by AAndyProgram** [comment]
You're welcome 😊
