### ISSUE TITLE
[BUG] Instagram Reels not downloading

### ISSUE THREAD

**Issue by yohuan94** [AAndyProgram/SCrawler#212]
Unsure if my settings are bad but even with reels ticked in the setting for Instagram,

Reels seem to not be downloading at all.

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/SCrawler/blob/main/FAQ.md#how-to-report-a-problem

**Comment by yohuan94** [comment]
Issue: 
Only downloads 58 videos out of the 200+ reels

URL:
https://www.instagram.com/lunalovekiss_/

LOGS:
None

Environment:
SCrawler v2024.10.24.0 (x64)
OS: Microsoft Windows 11 Pro (x64)
ffmpeg version: ffmpeg version 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
yt-dlp version: 2024.10.22
gallery-dl version: 1.27.6
cURL version: curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Comment by AAndyProgram** [comment]
**Not confirmed.** 158/158 reels downloaded. If you downloaded only 58 and also downloaded the timeline, then some reels were downloaded from the timeline to the video folder.

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg
