### ISSUE TITLE
Backup scrawler without opening app

### ISSUE THREAD

**Issue by sriwijaya572** [AAndyProgram/SCrawler#216]
Recently my PC had issue that render all program cant be opened (its windows 10) and i need to fresh install it

So is there another way to backup all my list inside?
🛐

**Comment by sriwijaya572** [comment]
Eh btw @AAndyProgram you could use my twitter account

Theres 2 of them for debug issue that causing it to only download several hundred tweet/media

**Comment by sriwijaya572** [comment]
Uhh.. And 1 last question
Is scrawler capable to delete my files?
Or if i uninstall it, will it delete all downloaded? 

Its so strange that all my downloaded file suddenly disappeared and folder name changed (leaving 1 loading image file)

**Comment by AAndyProgram** [comment]
> Is scrawler capable to delete my files?

What do you mean?

> Or if i uninstall it, will it delete all downloaded?

No, if the folder is not in the SCrawler folder. Just don't delete the data folder. SCrawler doesn't delete anything this way.

> Its so strange that all my downloaded file suddenly disappeared and folder name changed (leaving 1 loading image file)

👀 ????
