### ISSUE TITLE
[REQUEST] For Reddit, is it possible to make the file name the name of the post?

### ISSUE THREAD

**Issue by drag083** [AAndyProgram/SCrawler#23]
Firstly, great little tool you’ve built here! Simple to use and it just… works!

One question though: it appears files (at least from reddit) have a random name assigned, with the option to add a date in settings.

Similar tools have used the name of the post as the filename. Is it possible to add this as an option?

**Comment by AAndyProgram** [comment]
I'm not sure I completely understand you. The date/time naming is not random. Date/time is the date the post was published. Some users have asked me to add this option. Personally, I don't use it (name by date).

Do you mean add a post name or title? The name of the post is a six-letter text and does not contain any information. I don't want to add a post title because title can be too long, and I need to control the length of the text, forbidden symbols, etc.

I think the already existing date/time options are sufficient.

**Comment by drag083** [comment]
Understood, and thanks for the reply!

To clarify, I don‘t mean the date/time is random, I mean the default file name without that option enabled seems to be random (though this might be the actual filename when pulled directly from reddit).

And yes, I mean the post title being used as the file name, that’s what I was looking for.

If you take a look at some other tools like  [BDFR](https://github.com/aliparlakci/bulk-downloader-for-reddit), this allows you to use the following to create a naming scheme:

DATE
FLAIR
POSTID
REDDITOR
SUBREDDIT
TITLE
UPVOTES

Now I’m not looking for that kind of complexity here as I appreciate the simplicity of Scrawler and realise that BDFR is designed specifically for reddit. I believe for BDFR they simply replace any forbidden symbols (emojis, etc) and truncate the file length to keep it manageable.

As an example use case, I use BDFR (and now Scrawler) to download from the Wallpapers subreddit. With that subreddit, they include the Wallpaper dimensions in the post title, making sorting easier.

So it’s really just an option, a tick box to use the title as the file name… this was honestly the only feature I felt was missing when comparing the two! Keep up the great work! :)

**Comment by AAndyProgram** [comment]
>though this might be the actual filename when pulled directly from reddit

it is

>If you take a look at some other tools like [BDFR](https://github.com/aliparlakci/bulk-downloader-for-reddit), this allows you to use the following to create a naming scheme:

it's a CLI tool and I don't really want to test it, but BTFR and my tool are conceptually different.

>DATE
>FLAIR
>POSTID
>REDDITOR
>SUBREDDIT
>TITLE
>UPVOTES

this is too much. for the title only, at least the length of the text and the forbidden symbols must be checked.

I don't think I implement this feature (sorry). but you can develop a personal plugin and configure the name however you want

**Comment by drag083** [comment]
No problems at all, just thought I would raise and see if it was possible. Thanks!
