### ISSUE TITLE
Date and Time not added for Stories and Tagged Photos[BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#25]
I have it set to add date and time to the beginning of filenames. This is working for other things as normal (at least for twitter and instagram posts, both photos and videos), but this info does not get added for the newly-added instagram tagged photos or stories.

**Comment by TGJ64** [comment]
forgot to mention I am using version 3.0.0.5, I've not checked this on previous versions

**Comment by AAndyProgram** [comment]
Got it

**Comment by AAndyProgram** [comment]
It seems I fixed it. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest) and let me know if everything is ok.

**Comment by AAndyProgram** [comment]
Since I didn't receive your reply, I consider this issue resolved.
