### ISSUE TITLE
(minor) issues found setting up cookies and tokens [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#26]
I decided to start fresh with 3.0.0.5 and set everything up again from scratch cause I did something (not sure what but definitely just user error) that broke my previous version. While setting it up and going through the process for setting up cookies and authorization tokens I ran into a handful of minor issues that I was able to work around but figured I would mention here anyhow to make it easier for new users in future.

Issue 1: Twitter cookie "invalid"
I went to add my Twitter Cookie from Chrome as described in the wiki and received an error stating the following (I replaced the original string of numbers with 0 for privacy):
> The 'Value'='{"i_p":0000000000000,"i_l":1}' part of the cookie is invalid.
This value was the "g_state" value for the cookie. I simply removed that line and it worked fine, but perhaps that is something the program could do automatically in future.

Issue 2: on the 'Settings' wiki page for "How to find Twitter tokens" in step 6 it mentions "a query that starts with 'TwitterDetail?'...". There is no such query, and I believe it is supposed to be 'TweetDetail?' instead (which seems to work for the remaining steps).

Issue 3: It may be helpful to clarify in various places on the wiki and the program that x-ig-app-id and x-ig-www-claim are needed for instagram tagged photos and stories (and only needed for them). It took me a little while to realise I was missing them and that was why I couldn't get tagged photos or stories to work.

Issue 4: I wasn't able to find Insta hash 2 by following the guide on the wiki. No text with "query_hash=" appeared when I followed the steps. I personally don't use the saved posts functionality (I was only looking for it because I thought perhaps it was needed along with x-ig-app-id and x-ig-www-claim in order to get tagged/stories) so I didn't put much additional effort in once the instructions failed but wanted to mention it here in case it's one of those things that instagram quietly changed and you need to adjust for.

**Comment by AAndyProgram** [comment]
Issue 1:
>The 'Value'='{"i_p":0000000000000,"i_l":1}'

Just delete this cookie line (I'll add this to the wiki)

Issue 2. I already had an issue (#9) with TweetDetail. Then I updated the wiki. But now I don't understand what is not working.
What do you mean
>it is supposed to be 'TweetDetail?' instead

I hope you did not copy three dots?

>a query that starts with 'TwitterDetail?'...

Issue 3: It's already [there](https://github.com/AAndyProgram/SCrawler#settings-and-usage). But I'll update the Instagram settings wiki with this information.

Issue 4: Have you seen [step 4 from hash 2](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-instagram-hash-2)? **Open your saved Instagram posts.** Then only you can find this text.
The same for [stories authorization headers](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-instagram-stories-authorization-headers). **Open your saved Instagram tagged photos.**

----

Thank you for such detailed information. I really appreciate you and your every issue! Thank you for helping me improve SCrawler.

**Comment by TGJ64** [comment]
2: hadn't looked at issue #9 before and it looks like it references the same issue and resolves it, but when I go to https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens I still see this:
![image](https://user-images.githubusercontent.com/100350754/161448297-390012d3-9590-474d-84df-1918ac41a3f5.png)|

4: I was able to get the stories authorization headers no issue, it's only the query_hash= part that I'm not finding. It's still entirely possible I'm doing it wrong but I checked again doing the following (replacing my username with "MyUsername") :

- started on https://www.instagram.com/MyUsername (not saved posts just yet)
- opened developer tools, network tab
- 'cleared' network log (using the clear button)
- opened https://www.instagram.com/MyUsername/saved/
- CTRL+F (opened the search function within developer tools)
- searched "query_hash="
previously I found no results, this time I got two separate lines from a .js file, neither of which actually contained the full phrase "query_hash=", just "query" and "hash" both separately somewhere in the line.
It would probably be worthwhile for someone who uses Saved stories regularly to check if this is doable for them, it may be failing because I literally just saved a post to test this and otherwise haven't ever used the saved posts functionality.

**Comment by AAndyProgram** [comment]
2. I still don't understand what you don't understand? Sorry.
4. I just checked and found:

![Capture](https://user-images.githubusercontent.com/88590076/161450146-c2b35ee6-c903-4146-a090-181c847800b3.PNG)

**Comment by TGJ64** [comment]
Weird, I definitely don't see that when I search "query_hash=". Probably an issue on my end, I'm not too worried about it.


for 2, as seen highlighted in my screenshot above, the Wiki still says "TwitterDetail", but what I was trying to say (and as can be seen circled in your screenshot here https://github.com/AAndyProgram/SCrawler/issues/9#issuecomment-1026386187 ) is that it should actually say "TweetDetail". It's just a typo in the wiki instructions.

**Comment by AAndyProgram** [comment]
>the Wiki still says "TwitterDetail", but what I was trying to say (and as can be seen circled in your screenshot here https://github.com/AAndyProgram/SCrawler/issues/9#issuecomment-1026386187 ) is that it should actually say "TweetDetail".

Oh, I get it. Wow. It's a shame. I'll fix it on the wiki. Thank you! :frowning_face:

**Comment by AAndyProgram** [comment]
Fixed typo in [Twitter settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens)
