### ISSUE TITLE
Imgur data posted on Reddit fails to download.

### ISSUE THREAD

**Issue by unknown81311** [AAndyProgram/SCrawler#28]
**Is your feature request related to a problem? Please describe.**
Add a feature to reddit to be able to downland from imgur.com posts

**Describe the solution you'd like**
downland from imgur.com posts

**Additional context**
add a checkbox to create user panel for reddit for downloading imgur.com posts

**Comment by AAndyProgram** [comment]
Sorry, I don't quite understand what you want. Downloading imgur content is already fully supported by the Reddit downloader.

> to create user panel

What panel do you mean?

**Comment by unknown81311** [comment]
for me it doesn't work I checked the user on reddit and I didn't find the video downloaded to my folder so that's why I suggested it

**Comment by AAndyProgram** [comment]
Have you checked it:
>If imgur content is not downloading, please read [this chapter](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-imgur-client-id). You need to set up an Imgur client ID

**Comment by unknown81311** [comment]
ah

**Comment by unknown81311** [comment]
im not logged in btw if that matters

**Comment by AAndyProgram** [comment]
It doesn't matter.

**Comment by AAndyProgram** [comment]
Please set up your Imgur client ID and try downloading profile again. Please reply here if the issue is resolved or not. I'll be waiting for your reply.

**Comment by unknown81311** [comment]
looks like it works

**Comment by AAndyProgram** [comment]
Great! Thank you for your reply.
