### ISSUE TITLE
[REQUEST] Gay program?

### ISSUE THREAD

**Issue by username810** [AAndyProgram/SCrawler#30]
The information says you're gay. REMOVE THIS ASAP! I don't want to see that the program was made by a gay. Why did you write this?
В информации написано что ты гей. УБЕРИ ЭТО СРОЧНО НАХРЕН! Я не хочу видеть что программу сделал гей. Зачем ты это написал?

**Comment by AAndyProgram** [comment]
Why not, and why should I remove it?

**Comment by username810** [comment]
Because it's disgusting! I don't want to use the gay program, but I have to.
Are you really gay?
Потому что это противно! Я не хочу пользоваться гейской программой, но приходится.
А ты реально гей?

**Comment by AAndyProgram** [comment]
Excuse me, what? If you don't like the program, just don't use it.

**Comment by username810** [comment]
I like the program but I don't want to see that the program is designed by a gay!
Мне нравится программа но я не хочу видеть что программа разработана геем!

**Comment by AAndyProgram** [comment]
The program is presented as is. You can use it or not. It's only your choice.

**Comment by username810** [comment]
Are you really gay?
А ты реально гей?

**Comment by AAndyProgram** [comment]
Yes, I am. Why did you ask it?

**Comment by username810** [comment]
Ok bye
Ладно, пока

**Comment by AAndyProgram** [comment]
Goodbye. Have a nice day.

**Comment by unknown81311** [comment]
_what_
