### ISSUE TITLE
Some additional issues with date/time Instagram stories and tagged [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#32]
Sorry I never replied to your fix of issue #25, it did fix the original issue, I just hadn't had time to properly try it this past week.
There seems to be a couple smaller issues still with them though, from what I've seen:

Tagged Photos: doesn't add date/time to name if file is part of a "set" of photos (one instagram post containing multiple photos).

Stories: seems to sometimes leave duplicates behind after adding the date/time (i.e. a file named "filename123.png" exists, as well as a file named "220410_173000_filename123.png", if it was taken at 17:30:00 on april 10th 2022). Doesn't always happens but seems to happen at least a third of the time on the accounts I checked it on.

**Comment by AAndyProgram** [comment]
Hello.
You can reopen closed issue or comment there. Please do it next time.

>Tagged Photos: doesn't add date/time to name if file is part of a "set" of photos (one instagram post containing multiple photos).

Can you post the profile you are trying to download? A UserData file (xml) would also be helpful. Remember thet Instagram queries are very expensive.
You can text me in the matrix: https://matrix.to/#/@andyprogram:matrix.org

>Stories: seems to sometimes leave duplicates behind after adding the date/time (i.e. a file named "filename123.png" exists, as well as a file named "220410_173000_filename123.png", if it was taken at 17:30:00 on april 10th 2022).

I think this can happen if you change the naming mode and download the stories when some of them already exist.
Anyway, I need time to check it out.
