### ISSUE TITLE
Insta Stories only gets most recent 5 story selections [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#33]
The program only seems to grab the 5 most recent story "bubbles" (not sure what to call them, but the icons visible above posts) for a given user. All stories within each "bubble" are grabbed without issue and stored in a named folder without issue, but if a user has more than 5 "bubbles" anything after the 5th one is ignored.

Added a quick screengrab of what I mean in case my phrasing is too confusing. green-checkmarked "bubbles" are saved properly by the program, but every bubble after that is ignored.
![image](https://user-images.githubusercontent.com/100350754/162646515-1e03a207-b374-4b7b-add0-10f4eb9dc92d.png)

**Comment by AAndyProgram** [comment]
This is weird. I need time to check it out.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
