### ISSUE TITLE
Date/Time not being added [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#35]
Checked in both 3.0.0.8 and 3.0.0.9. Last version I know it definitely still worked properly in was 3.0.0.6, I skipped 3.0.0.7 so unsure if it was an issue then.

Steps taken: 
1) Fresh install, changed settings as below:
![image](https://user-images.githubusercontent.com/100350754/165016252-2c91ac64-2ce0-4413-93c7-dfcf1810c15b.png)

2) added an instagram user (haven't checked Twitter etc. yet) and downloaded.

3) confirmed that downloaded images don't have date/time added in filename

**Comment by AAndyProgram** [comment]
Continuation of issue #25.
You can use your own [script](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-use-the-script).
Instagram has very expensive queries. So, in order to debug this unnecessary feature for Instagram, I need a data file or I run my own queries. As long as no one wants to send me a data file and this feature is not valuable to me personally, I will not fix it, even if it contains an error.

**Comment by memnarch1337** [comment]
If I upload Data folders from versions 3.0.0.6-3.0.0.9, will that help?

**Comment by memnarch1337** [comment]
Here you go.
[dataFiles.zip](https://github.com/AAndyProgram/SCrawler/files/8717530/dataFiles.zip)

**Comment by AAndyProgram** [comment]
Found an error. Will be fixed in the next version.

**Comment by AAndyProgram** [comment]
@memnarch1337, it fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

----

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by blazer590** [comment]
Having the same issue in latest version 2022.7.7.0 date not adding to file name
[Settings.zip](https://github.com/AAndyProgram/SCrawler/files/9150905/Settings.zip)

**Comment by blazer590** [comment]
change file name is checked. add date/time to file name is checked. date and start position is checked. update user description everytime is also checked by default.

**Comment by AAndyProgram** [comment]
>bring back the date along with what probably is the time in military mode

It's not "military" time. It's just a [24-hour time format](https://en.wikipedia.org/wiki/24-hour_clock).

-----

**Confirmed.** If only the date is checked, the date not appended to the filename.

This is not a critical bug. I don't currently have time to look for bugs, so I can only suggest you use the date & time format as it works.

**Comment by AAndyProgram** [comment]
@blazer590, the bug has been identified. Will be fixed in the next version.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
