### ISSUE TITLE
Oauth/Token (twitter)

### ISSUE THREAD

**Issue by vincenzogianfelice** [AAndyProgram/SCrawler#42]
how can i access via token on twitter?

**Comment by AAndyProgram** [comment]
[How to find Twitter tokens](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens)

**Comment by vincenzogianfelice** [comment]
already done, but it doesn't work

**Comment by AAndyProgram** [comment]
Cookies are also required

**Comment by vincenzogianfelice** [comment]
yes, i did it

**Comment by AAndyProgram** [comment]
Okay, then post the LOG and the profile you are trying to download.

**Comment by AAndyProgram** [comment]
Forget to say that you need to remove cookies with a value in curly braces.

**Comment by vincenzogianfelice** [comment]
I tried again and it seems to work. Thanks
