### ISSUE TITLE
[REQUEST] Automatic downloads

### ISSUE THREAD

**Issue by memnarch1337** [AAndyProgram/SCrawler#44]
Since this program runs in the tray, can we get a setting to automatically grab new content every X minutes?

**Comment by AAndyProgram** [comment]
**Yes, it's in the plans.** Unfortunately, I cannot tell you how soon that will be. It certainly won't be in the next release.

**Comment by AAndyProgram** [comment]
Will be in the next version

**Comment by AAndyProgram** [comment]
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

About automation: https://github.com/AAndyProgram/SCrawler/wiki/Settings#automation

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
