### ISSUE TITLE
[REQUEST] Add site ifunny.co

### ISSUE THREAD

**Issue by DeckardTBechard** [AAndyProgram/SCrawler#45]
Requesting compatibility with ifunny.co.

I don't know to much about web APIs. but here's what I found:
https://www.npmjs.com/package/ifunny-web-api

I'd like to see mine and my friends old account content from back in 2013, but their site is so janky, you can't hardly scroll down a week back without issue.

I totally understand if you don't want to touch this site! I just thought I'd try to reach out.

**Comment by AAndyProgram** [comment]
No, sorry. I'm not interested in this site. But you (or your friends) can [develop a plugin](https://github.com/AAndyProgram/SCrawler/wiki/Plugins) for SCrawler.
