### ISSUE TITLE
[BUG] Unable to download Twitter media at full-resolution (4K)

### ISSUE THREAD

**Issue by tmpfx00** [AAndyProgram/SCrawler#46]
**Describe the bug**
SCrawler does not download media at full-resolution (4K). 

**To Reproduce**
1. Profile URL: https://twitter.com/nasahqphoto
2. Download selected (F5)
3. Check and compare resolution/size discrepancy in File Explorer. I.e. Extract one image from SCrawler output folder, and compare against the same image downloaded in chrome & IOS. In screenshots section below I compared FTFVFwyWYAEcIz4.

**Expected behavior**
I'd expect SCrawler in the original raw resolution (maximum attainable).

**Screenshots**

<img width="960" alt="Screenshot 2022-05-20 180253" src="https://user-images.githubusercontent.com/104393424/169505232-0ff063e4-6381-4e2f-ac44-8710c117c37f.png">

<img width="960" alt="Screenshot 2022-05-20 175750" src="https://user-images.githubusercontent.com/104393424/169504431-166c6894-f099-48b0-9689-e196221580da.png">

**Release information (please complete the following information):**
 - OS [Windows 10]
 - Architecture [x64]
 - Version [3.0.0.9]
 - NET.Framework version

**Additional context**
I've only seen this issue with images, I have not tested if videos are downloaded in full.

**Comment by AAndyProgram** [comment]
Yes, I know about this problem, but no one posted a link to the profile. Thanks for the profile link. The problem has been identified. The next version will fix it if everything is ok.

**Comment by tmpfx00** [comment]
Thanks for the reply, I appreciate your hard work. 

Just a heads up, not all photos on that profile are in 4K. I had to use the IOS Twitter app to determine this by holding on the image and tapping "Load in 4K" in the pop up.

**Comment by AAndyProgram** [comment]
Very interesting API!
Currently, image dimensions are obtained using this function. By default, almost every image on Twitter has size options: ```thumb```, ```small```, ```medium```, ```large```. SCrawler gets these sizes and determines the best one. When this happens, the following text is appended to the image URL: ```?format=jpg&name=large```. As a result, we have the following URL: ```https://pbs.twimg.com/media/SomeImage?format=jpg&name=large```.
https://github.com/AAndyProgram/SCrawler/blob/f491e03812166c8d08698172daefac3f3c5f3f26/SCrawler/API/Twitter/UserData.vb#L130-L149

But it looks like every photo with the additional query ```4096x4096``` (```https://pbs.twimg.com/media/SomeImage?format=jpg&name=4096x4096```) provides a full photo. I tested it on 10 photos and each one opens at its original size.

**Comment by AAndyProgram** [comment]
I fixed it, but a few days for tests

**Comment by tmpfx00** [comment]
That is very interesting, I'm amazed how quickly you fixed it! It's great to see active devs in the community.

I don't really understand programming and API's, but would the 4096x4096 query still work for non-4K images or would the request error out?

**Comment by AAndyProgram** [comment]
> I'm amazed how quickly you fixed it!

I could have fixed it sooner if someone sent me the profile URL like you did.

> It's great to see active devs in the community.

Thank you 😊 

> I don't really understand programming and API's, but would the 4096x4096 query still work for non-4K images or would the request error out?

I tested it and yes, it also works with non-4K images. But I didn't remove the function of determining the size. I expanded it and added a special checker. So if the image is not 4K, ```large``` (or any other size) will be appended to the image URL.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**Comment by tmpfx00** [comment]
Works like a charm! Thank you so much!

**Comment by AAndyProgram** [comment]
Thank for your help too.

BTW, if you like SCrawler, please like the program on this site: https://alternativeto.net/software/scrawler/about/.
