### ISSUE TITLE
Need Help- Understanding the usage of SCrawler

### ISSUE THREAD

**Issue by mdwala** [AAndyProgram/SCrawler#48]
Hey All,

I read the guide multiple times but do not get how this actually works. None of the features is settling in my congested mind. Please help.
I would like to know how to use this app. This thread might be long and sorry for that. I will be posting the question as we go, I am a system admin and should not be much more difficult to explain to me.

**Twitter:** (I have added both tokens and cookies and see no entry in the log)
1. At first I am trying to download what is posted by whoever I am following on Twitter. I am not sure if this is possible and how to do it. If not any other way to do it?
2. ~~I tried to Like a few videos in my profile and want to download them automatically. So went to "Saved Post" and click on the Green Play button. Nothing happens and just shows "Downloading saved twitter posts is completed" and no logs.~~
3. ~~I added another user who has multiple videos posted. But nothing downloads in right-click option "Download Data" or "Download Data limit with 1000". But downloads with "Download data to the Date". Can't understand why. Again log is clear.~~

**General:**
4. What is the actual meaning of "User"? Does that mean actual individual usernames we would like to get content from? Example Reddit-reddit.com/u/xyz?
5. What is Channel? Why there is a Reddit icon for that? Does this mean subreddit?

Once I am able to get point 1 and then I will explore further.

Version:SCrawler_3.0.0.10_x64

**Edit: I have removed some questions as reverting back to 3.0.0.9 solved it for now. 
I wish there is a video explaining how it works.**

**Comment by AAndyProgram** [comment]
1. SCrawler does not parse your following accounts. You need to add an account to SCrawler, select it and click the "Download" button.
2. SCrawler will not download media that you have set "Like". Saved posts means [Twitter bookmarks](https://twitter.com/i/bookmarks). You need to click "Bookmark" on the tweet. You also need to set up ```Twitter saved posts user name```. Open your twitter settings and check.
3. That is impossible. The SCrawler either downloads or it doesn't. If the data is downloaded using ```Download data to the Date```, then a regular (limited or not, doesn't matter) download must also download the content.
4. User patterns are described [here](https://github.com/AAndyProgram/SCrawler/wiki/Users#creating-user) and [here](https://github.com/AAndyProgram/SCrawler#settings-and-usage)
5. Yes, that means subreddit.

I suggest you also read the full [guide](https://github.com/AAndyProgram/SCrawler/wiki) and the following resources: [ReadMe](https://github.com/AAndyProgram/SCrawler/blob/main/README.md), [FAQ](https://github.com/AAndyProgram/SCrawler/blob/main/FAQ.md)

**Comment by AAndyProgram** [comment]
> I have removed some questions

Please, don't do this. Don't remove parts of the message. I don't sit here and watch who does what. If you edit a message, I don't get a notification and can't help you. Just reply to my messages.

>reverting back to 3.0.0.9 solved it for now

This is weird. Nothing has changed in 3.0.0.9 and 3.0.0.10.

>I wish there is a video explaining how it works.

No

**Comment by AAndyProgram** [comment]
You didn't upset me. Feel free to ask me. 😊 

Glad everything is working.

I asked not to remove parts of the messages because some other users might have the same problem and because I don't get notified when you change a message so I can't help you.

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
