### ISSUE TITLE
[BUG] Twitter gif download?

### ISSUE THREAD

**Issue by Disorbs** [AAndyProgram/SCrawler#53]
**Is your feature request related to a problem? Please describe.**
When a twitter profile uploads a gif the program detects it as just a jpeg image and downloads it like that rather than a gif.

**Describe the solution you'd like**
would be nice if it can download it as a gif.

**Describe alternatives you've considered**
maybe convert it to a mp4 at least.

**Comment by AAndyProgram** [comment]
I need a profile URL and a post URL containing a gif.

**Comment by Disorbs** [comment]
here is an example https://twitter.com/Vehicon/status/1428598026700869632

**Comment by AAndyProgram** [comment]
The problem has been identified. The next version will fix it if everything is ok.

**Comment by AAndyProgram** [comment]
I can only download in mp4. Twitter, as far as I can see, converts gif to mp4 (maybe for compatibility reasons or something) and unfortunately when I try to save this video as a gif, the downloaded file doesn't play.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
