### ISSUE TITLE
Option to embed metadata parameters to files [REQUEST]

### ISSUE THREAD

**Issue by tmpfx00** [AAndyProgram/SCrawler#55]
**Is your feature request related to a problem? Please describe.**
I feel like a lot of users of SCrawler use it to make account backups. However, SCrawler only saves the media and date acquired; this is fine as I can go back to their Twitter account and look for more information. However, when accounts are deleted/removed, I often want to know the context behind the images (i.e. title, uploader, date acquired etc.). 

**Describe the solution you'd like**
It would be cool if a feature was added in the SCrawler "create user" window that allowed an option to embed metadata into each individual image/video file. This could include **Title** (caption), **Authors** (username), **Program Name** (SCrawler), **Date acquired** (post date & time).

**Additional context**
![Screenshot 2022-06-13 155500](https://user-images.githubusercontent.com/104393424/173306443-3ec48fb6-7682-4dac-9e99-b3e93390a6ca.png)

I know this is a continuation of issue #35 and issue #36. But I thought I'd make a feature request if you're interested in implementing it in the future.

**Comment by AAndyProgram** [comment]
I don't know. You know, in December and January I actually thought about. But I declined this idea for several reasons.

Images files metadata editing has an ugly environment. To make it more convenient and neat, I need to use another library. And it's not a Microsoft library. I used this library for video files before in another program. It also has the ability to do the same for images. In January or February, I tried to implement this in SCrawler, but I didn't figure out how it works. It works very poorly with images and is not native.

So, in order to do what you want, I need the time and desire to learn this library and its functions. Currently I have neither the time nor the desire.

Btw, in your picture, except Title and Tags, all other selected fields are fields of this data type only (jpg, jpeg, png).

**Comment by tmpfx00** [comment]
Oh, I didn’t realise it was that involved/complicated. Hopefully a Microsoft library is made in the future, or a simpler solution is found. Again, it’s not a major issue/necessity but just a nice-to-have feature.

A potential simpler solution could be to write those parameters into individual .txt or .json files within the same directory as the videos/images 
(e.g. FUvqw6qWAAEW0gj.jpg & FUvqw6qWAAEW0gj.json). This would allow for even more data to be scraped/saved (i.e. comments, retweets, likes, tags etc.). 

Also, I thought I’d list the possible types of metadata in that screenshot. I didn’t know metadata fields changed based on file type. In all seriousness though, I agree with you that Title and Date acquired are the only useful fields anyway.

**Comment by AAndyProgram** [comment]
>A potential simpler solution could be to write those parameters into individual .txt or .json files within the same directory as the videos/images (e.g. FUvqw6qWAAEW0gj.jpg & FUvqw6qWAAEW0gj.json).

It's easy. This I can do.

>i.e. comments, retweets, likes, tags etc.

Comments - definitely NO! Retweets, likes? What for? What valuable information do you expect from them? Title, description, date - yes, this is important information. But likes, retweets....

>Thanks for considering it :)

You are welcome. I've added the label "future" to this issue, so maybe I'll come back to it someday.

----

**Btw, did you like SCrawler on [this site](https://alternativeto.net/software/scrawler/about/)?** 😊

**Comment by tmpfx00** [comment]
> Comments - definitely NO! Retweets, likes? What for? What valuable information do you expect from them? Title, description, date - yes, this is important information. But likes, retweets....
> As I said, title and date are the only useful information I need... I cannot speak for others and their needs. However, other crawlers such as Instaloader have the option to save comments, likes etc. so some must find it valuable. I was simply highlighting how .json files may be a better solution since you aren't limited to the standardised metadata fields and thus, can potentially store more information if required.

**Comment by AAndyProgram** [comment]
Btw, I forgot to say, the date is already in the user settings folder, in the Username_Data.xml file. This is not json, but xml is no worse.
