### ISSUE TITLE
[NEED HELP] Doesn't seem to be working for Xvideos channels

### ISSUE THREAD

**Issue by masterofobzene** [AAndyProgram/SCrawler#56]
**To Reproduce**
1. Profile URL: https://www.xvideos.com/model-channels/lucybbeth#_tabVideos
2. Do something
3. See error

**Release information (please complete the following information):**
 - OS [e.g. Windows 10]
 - Architecture [x64]

**Comment by AAndyProgram** [comment]
When the files are actually downloading, the information will be displayed. Just wait a little.

**Comment by AAndyProgram** [comment]
**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
