### ISSUE TITLE
[REQUEST] FPS selection when downloading from twitter

### ISSUE THREAD

**Issue by n00nanoo** [AAndyProgram/SCrawler#58]
There is some lossy frames when downloading videos from twitter as it strictly converts videos to 30 fps.

**Comment by AAndyProgram** [comment]
Unfortunately, I haven't seen this option of the video on Twitter. The Scrawler downloads a file received from Twitter. If this option is not available in the site's response, I can't help you. I can only suggest that you use a converter program to convert the video to the FPS you need.

**Comment by 963358** [comment]
how is ffmpeg used? It has an option to set a custom fps.

**Comment by n00nanoo** [comment]
How is ffmpeg being used ? It has an option to download videos at a set frame rate.
