### ISSUE TITLE
Stop all jobs option [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#59]
This is fairly minor as far as features go but the Stop button seems to only stop the current job. I can understand that being a useful feature in some situations but generally if I'm trying to Stop a job I want all of them stopped, and it usually takes a few moments before the active job can properly stop (which adds up quickly if you've hit download on many profiles).

I imagine this basically being a Stop All button, acting like the current Stop button for the active job but then just removing all the following jobs from the queue before they even start, so it should only take about the same time as the current Stop routine (though its possible that code-wise this is more complicated than that)

**Comment by AAndyProgram** [comment]
This looks like a bug. Actually, I personally haven't used the 'Stop' function for a long time and could have accidentally miss this bug. You are right. By clicking on this button, all active jobs must be stopped and removed from the downloader. I need time to find an error.

**Comment by AAndyProgram** [comment]
I don't see an error. Did you see this bug in routine (manual download) or with(in) the AutoDownloader?

**Comment by AAndyProgram** [comment]
To find an error I need more Information:
1. How many profiles are you downloading at this time (approx. value, eg 10-20-100-500...)?
2. Are there Instagram profiles and profiles of other sites in this download session, or only Instagram profiles, or only profiles without Instagram accounts?
3. Did AutoDownloader work at that time?
4. If yes, was it started before you started manually downloading, or after?

**Comment by TGJ64** [comment]
~40 instagram profiles. No other profiles at the moment. I've been only really using the stop button when I hit Download All or Download Selected and then realise that the Hash was (incorrectly) reset automatically, so it's possible it only happens when there's a Hash issue?

I haven't used the AutoDownloader yet.

**Comment by AAndyProgram** [comment]
No, this button must stop all download tasks. I don't understand why it doesn't work in your case. This button is independent of Instagram or any other site or values.

https://github.com/AAndyProgram/SCrawler/blob/ab020d9b5f8af44f1963be602526806e8e827837/SCrawler/Download/TDownloader.vb#L308-L314

**Comment by AAndyProgram** [comment]
BTW, ignore Hash issues in the log for a while. In the next version, I'll try to add more information about Instagram errors to determine which ones are valuable. I guess some of the errors are wrong.

**Comment by AAndyProgram** [comment]
BTW, are you sure you pressed the 'Stop' button? I mean was this button active or inactive (grey colored) when you click it? I ask because I found a problem with the activation/deactivation of this button.
