### ISSUE TITLE
[BUG] Download Instagram saved posts does not work.

### ISSUE THREAD

**Issue by Arthurpmrs** [AAndyProgram/SCrawler#67]
Hello, first I want to thank you for the nice program you developed. I'm trying to download my instagram saved posts, but when I click to start the download it says "Instagram Images: 0; Videos: 0" as shown below:

![image](https://user-images.githubusercontent.com/31834336/187803556-e5f72f41-97b1-4f82-86d0-5bfa0069ed7d.png)

1. In the configuration I added the cookies, copying from Google Chrome.
2. Added Hash, Hash 2, x-csrftoken, x-ig-app-id, ix-ig-www-claim and my own username (only the username not the URL)
3. Clicked Ok to save (didn't change anything else).
4. Clicked the Bookmark icon
5. Clicked the green button on the window to download instagram saved posts, the message above was showed.

There were no logs in the log window.

**Release information (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 2022.8.28.0_x64

About the .NET Framework version:
I checked in my Windows/Microsoft.NET folder and the highest version listed is v4.0.30319. However, when I downloaded the .NET runtime v4.6.1 (in this link: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net461) and tried to install it, this message shows:

![image](https://user-images.githubusercontent.com/31834336/187804665-bee9bfb4-5dfc-42a5-bb73-fe2ec226a687.png)

PS:
I triple checked all my credentials.
I also copied the ffmpeg.exe to the folder.
Downloading my own pictures from my profile worked fine.

**Comment by AAndyProgram** [comment]
**Confirmed.**
I need time to determine what has changed on Instagram.

**Comment by Arthurpmrs** [comment]
Thanks!
Ps: I didn't notice the text in the second screenshot was in Portuguese. It says "The .NET 4.6.1 or a newer version is already installed in this computer".

**Comment by AAndyProgram** [comment]
Instagram has made changes again. Good news: I fixed an issue (soon I'll publish a new release (need time for tests)).

**Comment by Arthurpmrs** [comment]
Thank you very much!

**Comment by AAndyProgram** [comment]
I need a few days. I started adding missing posts functionality to track and manage posts that weren't downloaded. So when I'm done, I'll post a new release.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

Sorry for taking so long. I started adding another feature that I've wanted to add for a long time and decided to post a new release when I'm done. So, I'm done. Try the new feature - [Feed](https://github.com/AAndyProgram/SCrawler/wiki#feed).

----

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by Arthurpmrs** [comment]
Hello, thank you very much!

Sadly, I could not make it work. I'm probably doing something wrong here. I tried rearranging the hash values, tried re-adding the cookies, tried more than one account. Now the saved dialog box says: "Instagram downloading started" but nothing happens.

**Comment by AAndyProgram** [comment]
I'm sorry, but I tried right now and the saved photos were downloaded. Have you added your username (```Saved posts username```) to your Instagram settings?
Instagram saved posts require all tokens, cookies, username and Hash2.

**Comment by AAndyProgram** [comment]
Btw, have you waited enough? Because the text "**Instagram downloading started**" is displayed when the downloading is just started.
- If an error is found, this text will be replaced with this "**Instagram downloading error**". Also, information about the error will be added to the log.
- When the download is complete, this text will be displayed "**Instagram Images: 10; Videos: 0**".
- If any credentials are missing, this text: "**Host Instagram is not ready**".
- If you are currently downloading any Instagram profiles, this text: "**Host Instagram is unavailable**". You cannot download saved **Instagram** posts while any **Instagram** profiles are currently downloading.

If you have a lot of saved photos, this may take some time.

**Comment by Arthurpmrs** [comment]
I did wait for some time, but I have a lot of saved posts (possibly more than 10k). I'm gonna try it again tomorrow. Thank you!

**Comment by Arthurpmrs** [comment]
Hey, I created another account and saved about 50 posts to test it. It works! I'm so sorry for the trouble. The other two accounts that I tested may have more than 10k and 50k posts saved. I was not waiting long enough. Thank you! I'm going to let it download for the whole day tomorrow on my main account.

**Comment by AAndyProgram** [comment]
>I have a lot of saved posts (possibly more than 10k)

WOW!! You'll have to wait for SCrawler to download SO many photos, many, many days!

>I'm going to let it download for the whole day tomorrow on my main account.

I think one day is not enough

Look, I'll try to explain. For one request, I receive 50 posts. Unfortunately, I can't get the complete information about the posts with a single request. Complete information means that this site response doesn't provide information about the image gallery (carousel media) of the post. In this case, I can only collect post IDs from those responses. And in the next step, SCrawler will start downloading information about each post. This means that for **each post** in your array (10k), the site will be asked for information about that post.

You can read about limits on Instagram [here](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-limits).

You can set ```Post limit timer``` ([Instagram settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram)) to the lowest value (10000). **I have not tested the lowest value and cannot assure you that your account will not be banned.** But for some information that I've read, this value (10000) is fine. 60000 is a safe value.

This is a rough estimate of how long parsing will take:
Value = **60000**: ((10000-195)*60)/60/60/24 ~= 6 days + 19hrs
Value = **10000**: ((10000-195)*10)/60/60/24 ~= 1 days + 3hrs
