### ISSUE TITLE
[BUG] RedGifs data is not downloading

### ISSUE THREAD

**Issue by AAndyProgram** [AAndyProgram/SCrawler#69]
**On August 31, RedGifs changed the API requirements. These changes cause an error on downloading.** Unfortunately, at this time, I still cannot resolve this issue.

Starting from version [2022.9.8.0](https://github.com/AAndyProgram/SCrawler/releases/tag/2022.9.8.0), downloading data from the RedGifs site is temporary disabled. You can still add RedGifs profiles, but they won't download. You will be able to download them when this issue is fixed.

**If you know how to solve this issue, you can post a suggestion in a comment on this post.**

**Comment by AAndyProgram** [comment]
Still nothing has changed. I tried downloading the HTML page and parsing it and it worked for a few minutes, but then they blocked my IP (I think) and I started getting the "Invalid signature" error again.

**Comment by The-Morrighan** [comment]
I've been trying to resolve this as well, mostly via ideas posted here: [](https://www.reddit.com/r/DataHoarder/comments/x67zfo/redgifs_api_now_blocked_from_hotlinking_anyone/)
and
here: [](https://github.com/RipMeApp/ripme/issues/1994#issuecomment-1235137334)
and via their api page (all of which you've probably already seen, but I thought I'd share just in case) [](https://github.com/Redgifs/api/wiki/API-access)

**Comment by AAndyProgram** [comment]
Already seen and follow. This doesn't work

**Comment by AAndyProgram** [comment]
Hello @The-Morrighan 
Any news?

**Comment by CypherpunkSamurai** [comment]
Contrary to the comments on the reddit post, I was right. The Bearer token works permanently.

I'm not sure how long, but we know how to create the token (as mentioned above). Even if the token doesn't work we can create it on the fly. 

Sounds like it's time to Code

https://www.apirequest.io/634a3e05e2a8841f58a6c4f8?at=eyJhcHAiOiI2MzRhM2UwNWUyYTg4NDFmNThhNmM0ZjgiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIwOjAiLCJwZXJtaXNzaW9ucyI6eyIwOjAiOnsic2NwIjoiY3JlYXRlOndvcmtzcGFjZXMgcmVhZDp3b3Jrc3BhY2VzIHVwZGF0ZTp3b3Jrc3BhY2VzIGRlbGV0ZTp3b3Jrc3BhY2VzIn19LCJleHAiOjE2NjgzODQwMDAsImp0aSI6IjNlZjQzMmNlLTg4YjktNGVmMC05MGE0LWQ4ZDUyMmQwOTNlOSJ9.65sI_NpD54L6yHOgMEVZ_ZT7w5MK1MMyXzzjw9QwvK8

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by Ihatetotank** [comment]
Just tried to rip https://www.reddit.com/user/slaysheslays and it didn't capture any video from Redgifs

**Comment by AAndyProgram** [comment]
**It seems RedGifs has changed something again**. Today I started getting a 401 (Unauthorized) error. I think authorization needs more than a bearer token and cookies.

**FYI**. Cookies are valid for a very short term. The bearer token refreshes every request. I think one bearer token could be valid for the duration of the cookies, but I'm not sure.

**If you know how to solve this issue, you can post a suggestion in a comment on this post.**

**Comment by AAndyProgram** [comment]
Hm... RedGifs seems to still work. RedGifs media posted on Reddit download without problems. The authorization error only occurs when loading a RedGifs profile.
It can't get data for request `https://api.redgifs.com/v2/users/UserName/search?order=recent`

**Comment by altbdoor** [comment]
A plain curl seems to work fine. Maybe RedGifs were still experimenting stuff on their servers?

```sh
$ curl 'https://api.redgifs.com/v2/users/celebs/search?order=recent'
{"page":1,"pages":12,"total":341,"gifs":[{"id":"oblongclosesiskin","createDate":1651916881, #snib
```

**Comment by AAndyProgram** [comment]
You are right! It doesn't require cookies and token! Just a simple request without authorization! Brilliant! Thank you!
Actually, I didn't even think about the test without credentials!

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

----

Get RedGifs [temporary token](https://github.com/Redgifs/api/wiki/Temporary-tokens)
```HTTP
GET /v2/auth/temporary HTTP/1.1
Host: api.redgifs.com
Accept: application/json

{
 "token":"...",
 "addr":"2a00::579f:3c01:b94e",
 "agent":"curl/7.81.0",
 "rtfm":"https://github.com/Redgifs/api/wiki/API-access"
}
```

Get specific post data (**token** required): ```https://api.redgifs.com/v2/gifs/<PostID>?views=yes&users=yes```
Get a list of the user's posts (**nothing** required): ```https://api.redgifs.com/v2/users/<UserID>/search?order=recent```

**Comment by Ihatetotank** [comment]
Dang, did it break again?

**Comment by AAndyProgram** [comment]
Yes

**Comment by AAndyProgram** [comment]
Fixed... Again... 😕  Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
🎄 Happy new year! 🎄
