### ISSUE TITLE
[BUG] Instagram posts not updating after initial download if there are pinned posts

### ISSUE THREAD

**Issue by S-rg-n** [AAndyProgram/SCrawler#70]
It seems that if a profile has any pinned posts, all of the posts present at initial download will get downloaded as expected. However, posts added afterwards aren't downloaded when updating those users.

**Comment by AAndyProgram** [comment]
It's possible. I need profiles with pinned posts.

**Comment by S-rg-n** [comment]
Two accounts with pinned posts:
https://www.instagram.com/bryceandrewmusic/
https://www.instagram.com/urliability/

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
