### ISSUE TITLE
[BUG] On LPSG only downloading inline images

### ISSUE THREAD

**Issue by S-rg-n** [AAndyProgram/SCrawler#74]
Posts with pictures posted inline get downloaded without issues, but if the posts have the pictures as attachments they do no get downloaded. Video posts are also not being downloaded.

**Comment by AAndyProgram** [comment]
Yes, I know.
1. Some images won't download. I have no time to fix it.
2. Video posts are not downloaded because they are paid content on LPSG.

Actually, this plugin was developed more as an example than as a real plugin.

**Comment by S-rg-n** [comment]
They aren't quite paid, just only able to be downloaded at specific times. Paid just removes the time limitation. Does it not use login info when cookies are added? (to bypass limitations) I suspect that is also why it can't download regular attachments. Since only logged in users can see them.

And unfortunate if you don't have time to fix it, but understandable since it is pretty niche compared to the other plugins.

**Comment by AAndyProgram** [comment]
I have not seen any videos that can be viewed on this site for free. I developed this plugin in 1.5hrs. I was interested in several topics. The result of the download satisfied me. I know some images are missing. But for me this is not a priority site.

I think I'll fix it when I have time, but not sure exactly when. Sorry.

You can also develop your own SCrawler [plugin](https://github.com/AAndyProgram/SCrawler/wiki/Plugins) if you like.

**Comment by S-rg-n** [comment]
No worries, it's low priority for me too lol. I just wanted to make sure you knew there was an issue at all (which you did). And for future reference, the videos are free to watch/download if the current time ends in a 3 or 7, for example 12:03, 12:27

**Comment by AAndyProgram** [comment]
Okay. I'm tagging `pending` and closing this issue until I have time.
