### ISSUE TITLE
Not downloading "friends only" Tiktok posts [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#80]
I know the Tiktok feature is new and still being worked on so maybe this is already in progress but I noticed that when I tried it today for the first time it isn't downloading posts that I can see that are set as "friends only" (which tiktok defines as you and the user who posted both follow each other). I know that some tiktokers also post "followers only" videos though I've not yet found an example of that to test.

One thing to note, the log did mention ``Some posts didn't download. You can see them in the 'Missing posts' form.`` but I've not been able to find a "missing posts" form. Possibly that form mentions these posts? I unfortunately tested the tiktok download at the same time as some other downloads were running so I can't be sure the two things are related.

**Comment by AAndyProgram** [comment]
Missing posts: https://github.com/AAndyProgram/SCrawler/wiki#missing-posts
**Before** publishing a new release, I update the guide. So when you see a new release, the new features (if they exist) have already been added to the wiki!

TikTok doesn't have proper API documentation. I even still [can't download all user videos](https://github.com/AAndyProgram/SCrawler/issues/75). I don't know about "friends only". But I can say just one thing: until I understand how to get the correct json response and how the `cursor` parameter works, there is nothing I can do. Sorry.

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
