### ISSUE TITLE
Instagram tagged photo dates not consistent

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#81]
I was running a test with a fresh install of the program and discovered that some tagged photos had different dates from a previous version of the program. It seemed like while older tagged photos had dates that lines up with when they were posted, more recently-tagged photos were being given the date they were downloaded by the program rather than when they were posted.

This may be just my interpretation of what the "date" for a tagged photo should be. I would want the date to be the date that the tagged photo was posted (not the date it was tagged or the date that it was downloaded by the scrawler program), and maybe that doesn't work well with how the program runs?

**Comment by AAndyProgram** [comment]
I have already [answered](https://github.com/AAndyProgram/SCrawler/issues/55) this question! SCrawler does not change files' metadata.

**Comment by TGJ64** [comment]
I am not referring to the metadata, apologies for the confusion, I'm referring to the date/time that can be added to the filename. 
For every other type of photo/video (twitter, reddit, tiktok, and regular instagram posts/stories) the "date" added to the filename is the date that it was posted. But for instagram _tagged_ photos, the "date" added to the filename is inconsistent and seems to often just be the date that scrawler downloaded the file. 
Ideally, I'd like it to be the date that the tagged photo was first posted, like with all the others.

**Comment by AAndyProgram** [comment]
Got it. Sorry for the misunderstanding. Tagged posts are processed by this function:
https://github.com/AAndyProgram/SCrawler/blob/7d169acebc91ad777dddea9b628936ec5a199748/SCrawler/API/Instagram/UserData.vb#L512-L529
Maybe Instagram has changed something again. As you can see, the date can be extracted from one of the following response fields: `taken_at`, `imported_taken_at`, `device_timestamp`.
I'll take another look at the response and if I see changes, I'll fix it, of course. But if these fields are still in the response, I won't fix it, sorry. As I have said many times, Instagram queries are very expensive. You can verify the post date in the UserName_Data.xml. If the date exists, I guess the fields exist too.

**Comment by AAndyProgram** [comment]
Btw, can you check if these photos (with the wrong timestamp) are carousel media (more than one photo and/or video in one post)?

**Comment by AAndyProgram** [comment]
Did you check?

**Comment by AAndyProgram** [comment]
Since I didn't receive your reply, I consider this issue resolved.
