### ISSUE TITLE
[BUG] Twitter parsing all tweets but not downloading.

### ISSUE THREAD

**Issue by Rootkit-** [AAndyProgram/SCrawler#85]
Creates post posts.txt and xml file with valid links to download
I run download. I'm 99% sure I setup cookies bearer correctly IE setup for other sites before and infact I had done it once before on twitter a few months ago.

User: remarkablepaper (site: Twitter)
Labels: No Parsed
Path: K:\!jd\Twitter\remarkablepaper\
Total downloaded (0):
Pictures: 0
Videos: 0
Last updated at: not yet!
Pictures: 0
Videos: 0
![image](https://user-images.githubusercontent.com/5389279/204159796-66af4900-d8f0-4528-b2e0-85ee065d1145.png)
![image](https://user-images.githubusercontent.com/5389279/204159718-01336a4b-609c-4188-88f2-02dfc6b4383d.png)
[image](https://user-images.githubusercontent.com/5389279/204159703-c4595496-c5f8-43f8-8475-cdc65df67190.png)
![image](https://user-images.githubusercontent.com/5389279/204159813-c86c2376-61c8-4e68-8551-301f528abab6.png)
![image](https://user-images.githubusercontent.com/5389279/204159823-97343aa7-1618-4eb1-8344-03c59ed7bdc3.png)
![image](https://user-images.githubusercontent.com/5389279/204159825-dc47b5fc-93df-4cab-8f26-2c34c989e195.png)

**Comment by AAndyProgram** [comment]
>I run download. I'm 99% sure I setup cookies bearer correctly IE setup for other sites before and infact I had done it once before on twitter a few months ago.

I'm sorry, but I'm not sure I understand you. You've been using SCrawler for a while and today is the first day you can't download Twitter posts. Am I correct? Did Twitter download everything correctly before?

As I can see from your screenshots, you have everything configured correctly. And LOG contains nothing.

>I setup cookies bearer correctly IE setup

What does it mean? Have you grabbed cookies from IE? I really doubt IE has the same cookies table as Chrome, Edge or Firfox. You should use one of these browsers, not IE.

I use SCrawler almost every day. Today I successfully downloaded 4 Twitter profiles. It is possible that some of your credentials have expired. Please update your credentials and try again. Also make sure the user you are trying to download has checked the `Download Images` and `Download videos` options. If the problem persists after this, please post the URL of the profile you are trying to download. If the problem goes away, please leave a comment anyway.

![User settings](https://raw.githubusercontent.com/AAndyProgram/SCrawler/main/ProgramScreenshots/CreateUserClear.png)

**Comment by AAndyProgram** [comment]
BTW, as I can see, you checked `Get user media only` in your Twitter settings. It means that only posts posted by the user will be downloaded. Retwits of other profiles will be ignored. This explains why your file contains post IDs. Verify this option in the user settings and make sure that the user posted something himself (https://twitter.com/UserName/media). If the user hasn't posted anything and you want to download their retweets, you need to uncheck this option.

To redownload this profile, you must remove it from SCrawler and add it again. Then download it.

**Comment by AAndyProgram** [comment]
If you tried to download this profile (https://twitter.com/remarkablepaper), I downloaded it right now and some images and videos were downloaded.

**Comment by Rootkit-** [comment]
Okay I see what I did. Thanks guys. Close.
