### ISSUE TITLE
Is it possible to download all of a user's posts?

### ISSUE THREAD

**Issue by OneSteelTank** [AAndyProgram/SCrawler#88]
I'm sorry if this is the wrong place to ask, but I'm confused by how to go about this. I think I've worked out how to download all the posts in a subreddit but I'm wondering how/if it's possible to download the posts from a single person

**Comment by AAndyProgram** [comment]
I'm not sure I understand you. Add user to SCrawler and download it.

**Comment by OneSteelTank** [comment]
![image](https://user-images.githubusercontent.com/30085240/205503787-32f8851d-9307-4ab7-aee1-2f3ff0463b1e.png)
like this? When I press OK and then press download it says "Download complete" but then I look in the folder and all I see is an XML file

**Comment by AAndyProgram** [comment]
If it's a user, why did you check the `Channel` option?!

**Comment by OneSteelTank** [comment]
Wow, for some reason I thought that I needed to select Channel to select Reddit. Thanks, that worked. Is it possible to get custom filenames? I want to be able to include things like the original post date

**Comment by AAndyProgram** [comment]
> Is it possible to get custom filenames? I want to be able to include things like the original post date

Look at the `Settings` - `Downloading` - `Change file names` option: https://github.com/AAndyProgram/SCrawler/wiki/Settings#downloading

**Comment by OneSteelTank** [comment]
Ok, thanks a bunch man. If there's a better place to ask future questions let me know, I'm sure this isn't the best place

**Comment by AAndyProgram** [comment]
I believe that users should ask their questions in the place that is most convenient for them. "Issues" is the right place. Some of the users prefer to ask a question in the [discussion](https://github.com/AAndyProgram/SCrawler/discussions) block.

I'm glad that everything works for you. Have a nice day. 😊 

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by OneSteelTank** [comment]
Thanks, I'll use that place from now on. I liked the program. Hope you have a nice day as well
