### ISSUE TITLE
twitter downloads not working. folder blank

### ISSUE THREAD

**Issue by ShiroUwUs7** [AAndyProgram/SCrawler#9]
twiter doesn't download any images no matter of who is added as the user.

**Comment by AAndyProgram** [comment]
Twitter requires [two tokens](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens) and [cookies](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-set-up-cookies) to download. Do you remember? I checked right now and downloaded media from twitter (images and videos).
Is there any data in the log? What version of the program are you using?

**Comment by ShiroUwUs7** [comment]
latest version I grabbed the 2 tokens and cookies but the in app browser fails so i have to manually get them via: "Get cookies.txt" extention

**Comment by ShiroUwUs7** [comment]
I use edge, and tried with chrome also but didn't find the lines.

**Comment by AAndyProgram** [comment]
> latest version I grabbed the 2 tokens and cookies but the in app browser fails so i have to manually get them via: "Get cookies.txt" extention

You don't need to use extensions. And I don't know what format they store cookies in.
I posted a guide on **[how to get cookies](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-set-up-cookies)**. It is very easy. Please just follow the guide!

>I use edge, and tried with chrome also but didn't find the lines.

Edge has exactly the same developer tools as Chrome
So did you get tokens or not?

>there is no twitterevents? under networking sadly.
>or TwitterDetails?

Open post in separated tab. Open developer tools (```Ctrl``` + ```I```). Go to the network tab. Clear everything you see (optional, you can skip this step). Refresh the page and find the fields.

**Comment by ShiroUwUs7** [comment]
![GPHLSF4 1](https://user-images.githubusercontent.com/53096166/151898153-a315307f-88e6-48db-a4a4-35043c304784.png)
there is no field for twitterdetails?

**Comment by AAndyProgram** [comment]
Look, I don't know what you're clicking on.
Repeat these steps STEP-BY-STEP:
1. Open https://twitter.com
2. Press ```Ctrl``` + ```I```
3. Go to the network tab
4. In the window where you have twitter open, click on first post you see (**CLICK ON THE POST DATE**)
5. Then look at the dev tools and in the first lines you will see what you need!
![Capture](https://user-images.githubusercontent.com/88590076/151899323-4f1258ee-057b-47dc-bb0c-8825318ec81d.PNG)

**Comment by AAndyProgram** [comment]
If you find [this guide](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens) confusing or missing important information, please post your version of the token guide and I'll fix it.

**Comment by ShiroUwUs7** [comment]
> If you find [this guide](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-twitter-tokens) confusing or missing important information, please post your version of the token guide and I'll fix it.

well i found the issue. your guide says "In the list on the left, find a query that starts with **TwitterDetails?**... and click on it "
instead of **"TweetDetail?"**

**Comment by AAndyProgram** [comment]
>your guide says "In the list on the left, find a query that starts with TwitterDetails?... and click on it "
instead of "TweetDetail?"

Thank you for your reply. Guide corrected.
