### ISSUE TITLE
[REQUEST] Add FFmpeg to x86 version

### ISSUE THREAD

**Issue by Zliced13** [AAndyProgram/SCrawler#96]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like FFmpeg to be added to the x86 version.

**Describe alternatives you've considered**
None.

**Additional context**
This FFmpeg build repository has support for x86 Windows OS.
https://github.com/yt-dlp/FFmpeg-Builds
x86 FFmpeg download link:
https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win32-gpl.zip

**Comment by AAndyProgram** [comment]
Okay I'll add it in the next version but only if you will give me feedback about the stability. I'm using [another developer's version](https://github.com/GyanD/codexffmpeg/releases/tag/2021-01-12-git-ca21cb1e36) and I am not sure if all the functions in the version you post are the same. Okay?

**Comment by Zliced13** [comment]
I will give you feedback about the stability. I will try to make time for it.

**Comment by AAndyProgram** [comment]
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest). I'll be waiting for your feedback. 😉 
🎄 Happy new year! 🎄 

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Comment by Zliced13** [comment]
Great to Hear I'll try it when I can.

**Comment by Zliced13** [comment]
@AAndyProgram It works very well as expected, The downloader was able to download the videos, and combine the audio and the video together using the x86 FFmpeg binary. Proof:
![(explorer)q626u7_12-26-2022](https://user-images.githubusercontent.com/101912712/209586497-b342e44b-5070-4da6-b444-3f3582cbe883.jpg)

**Comment by AAndyProgram** [comment]
I'm glad. Enjoy. 😊
