### ISSUE TITLE
Can't download from twitter anymore

### ISSUE THREAD

**Issue by Jasper42** [AAndyProgram/SCrawler#98]
I used to have no issues but it suddenly just stopped downloading from twitter. I'm not smart enough to figure out what's happening, please help.
[Log.txt](https://github.com/AAndyProgram/SCrawler/files/10352902/Log.txt)

**Comment by AAndyProgram** [comment]
There are no twitter errors in your log.
Look at [this thread](https://github.com/AAndyProgram/SCrawler/discussions/87). These guys had a similar problem. Try updating your credentials.

**Comment by Jasper42** [comment]
That was fast. THANKS! I updated my cookies and its working again.

**Comment by AAndyProgram** [comment]
You are welcome 😊 
**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**
